label natsuki_exclusive_1:
    scene bg club_day
    with dissolve_scene_half
    n "Ugh!"
    "I hear Natsuko utter an exasperated sigh from within the closet."
    "He seems to be annoyed by something."
    "I approach, in case he needs a hand."

    play music t6 fadeout 1
    scene bg closet
    with wipeleft_scene
    show natsuko 6x at t11
    mc "You need help looking for something in there?"
    n "Frigging Mateo!"
    n "He never puts my stuff back in the right spot!"
    n 5w "What's the point in keeping everything organized if he's just gonna go mess it all up?"
    "Natsuko slides a bunch of stacked books and boxes across the shelf."
    mc "Comics..."
    n 1k "You like comic books and manga, right?"
    mc "I dabble."
    mc "I was super into it when I was a kid until I moved on to video games."
    mc "But, I still have a collection that I flip through from time to time."
    n 3d "Well, I got 'em all!"
    n "Take a look for yourself."
    hide natsuko
    "He takes a few steps away from the closet so I can see the various box sets."
    mc "That's a pretty impressive collection."
    "I spot a lone volume of manga amidst a stack of various books on the side of one of the shelves."
    "Curious, I pull it out of the stack."
    show natsuko 5l zorder 2 at t11
    n "Hey, I was looking for that!"
    "I notice a box of manga in the closet that's missing a volume."
    "I take the liberty of slipping it into the empty slot."
    mc "There you go."
    n 1z "Thanks!"
    n 1l "That looks so much better."
    n 1d "Seeing a box set with one book missing annoys the hell out of me."
    mc "I know that feel."
    mc "You can ask Satori how many times I've flipped out on him for not putting one of my games back in the proper case or slot."
    "I take a closer look at one of the sets."
    "It appears to be a much older series than the others."
    mc "The Adventures of Kaptain Kid?"
    "It sounds kinda childish."
    "It must be out of my demographic."
    "That, or it just sucks."
    n 5t "Ehehe...that..."
    n 7t "That's the first manga set I ever got when I was a little kid."
    n "I'm sure the story doesn't hold up."
    n "And the humor is probably really cheesy."
    n 7m "But it's got sentimental value to me, you know?"
    mc "Funny...I never pegged you as a sensitive guy."
    n 5h "Well, I'm no wuss!"
    n "I'll fight if I have to!"
    n 7n "But I'm not a heartless jerk, either."
    mc "Hey, there's only one jerk in this club."
    mc "And it's not you."
    show natsuko 7ad
    mc "Besides, you don't need to worry about me judging a book by its cover."
    mc "The good stuff is always on the inside anyway."
    mc "In fact..."
    "I pull the first volume of Kaptain Kid from the box."
    mc "Why don't you take me on a little trip back to your childhood?"
    n 7k "...!"
    n 5l "R-really?"
    mc "Sure."
    mc "It'll be fun!"
    "I check out the front cover."
    "It features 4 teenage boys striking animated fight-poses."
    "It looks like any ninja series that caters to boys."
    mc "Come on!"
    "I grab Natsuko's arm and pull him out of the closet."

    show bg club_day
    with wipeleft_scene
    "I take a seat against the wall, beneath the windowsills."
    "I pat the ground next to me, signaling him to sit there."
    "He takes his seat."
    show natsuko 1ah
    n "Say, this is way better than using chairs!"
    mc "Right?"
    mc "It's easier for us both to see the book this way."
    n 1ad "Actually..."
    n 5ak "I meant, it's because we get to sit all close together like this."
    ##"He scootches closer until our legs are practically touching."
    "I kind of expected this level of flirtatiousness from him."
    "Not that it's a particularly bad thing."
    mc "Calm down, Casanova."
    mc "We're just reading a manga."
    show natsuko 1z
    "Natsuko giggles in amusement as I open the book."
    "He leans in a bit."
    show natsuko 1ac
    "He seems to be more eager to begin reading than I am."
    n 1ai "Man...how long has it been since I read this?"
    mc "Getting the nostalgic feels, are we?"
    n 1z "All the feels!"
    n "I don't think I've read this in..."
    n 5k "8 years? Whoa..."
    "I look at him curiously."
    "Now that it's been brought up, I can't help but wonder..."
    "How old is Natsuko anyway?"
    "Yeesh, that's probably something I should find out before I go any further with this..."
    mc "So...you were like... What?"
    mc "Five or six when you last read this?"
    show natsuko 6g
    "Natsuko suddenly shoots me an annoyed stare."
    n 6p "...Seriously?"
    n "You think I'm around fourteen years old?!"
    mc "N-no..."
    "Dammit...do I really not know how to count?"
    "Eight plus six is sixteen, right?"
    "No...what am I talking about?"
    "Eight...nine, ten, eleven, twelve, thirteen, fourteen..."
    "Gah! I suck at math!"
    "Natsuko visibly shudders."
    n 7w "Ugh, I'd HOPE you'd assume I'm older before trying to hit on me!"
    mc "Guh!"
    mc "That-that's not..."
    mc "I wasn't even..."
    mc "I didn't..."
    "My ability to articulate vanishes."
    "There's no recovery from this situation I've gotten myself into."
    "I mean...now I look like a total pervert."
    n 7q "Ten."
    mc "Jesus, you're TEN!?!?!"
    n 7p "What?"
    n 6v "NO!!!"
    n 3w "I mean, I was ten the last time I read this manga!"
    n 7x "Jeez! You're so weird!"
    mc "Ah--...so, you're 18?"
    n 7r "Yes. I am 18 years old. Sheesh."
    "I exhale."
    "I didn't even realize I was holding my breath."
    show natsuko 7ab
    "Natsuko looks at me with a mischievous expression."
    n 7ah "Hmm...I'd surf that."
    mc "Eh? Surf what?"
    n 5z "That wave of relief washing over you right now!"
    "He grins smugly, obviously quite proud of himself."
    "Meanwhile, my face couldn't be any redder."
    "Time to change the subject."
    mc "Whatever...are we reading this comic or not?"
    n 7y "Calm down, nothing's even happened yet."
    n 7l "We can still talk."
    mc "Well...what should I expect from this?"
    mc "Is there going to be a plot?"
    n 5c "Uh, of course there's going to be a plot."
    n 1k "It just takes a while to get to the good stuff."
    n 3j "Some stories start out really slow and simple."
    n "But it's only to help you get to know the characters."
    n "It's still entertaining."
    n 3l "Later on, when the action starts..."
    n "We dive deeper into their backstories and that's when all the cool fighting starts to happen."
    n 5z "That's what really makes it good! All those awesome battle scenes..."
    mc "That actually sounds pretty cool."
    n 7z "Ha! Just you wait!"
    "We read on for a few minutes."
    "I've finished a couple chapters at this point."
    "I glance over and jump a little."

    #show natsuko cg bg
    scene n_cg1_bg
    show n_cg1_base
    with dissolve_cg
    "Natsuko is staring right at my face."
    mc "...You, uh...need something?"
    show n_cg1_exp2 at cgfade
    n "Nope."
    n "I'm just watching you read."
    mc "Ah. That's not..."
    mc "Boring for you?"
    hide n_cg1_exp2
    show n_cg1_exp1 at cgfade
    n "Not at all."
    n "It's not every day I get to share my manga and comics with others."
    n "I'm having fun here."
    mc "Hmm. Well, I can see where you're coming from."
    mc "I get really happy when I can convince my friends to play a video game with me."
    hide n_cg1_exp1
    show n_cg1_exp2 at cgfade
    n "That must be nice."
    n "Being able to get your friends to experience something you're passionate about."
    mc "You don't share your comics and manga with your friends?"
    hide n_cg1_exp2
    show n_cg1_exp3 at cgfade
    n "I wish."
    n "Most people grow out of comics and manga by a certain age, so everyone just thinks I'm immature for being into it."
    n "Pisses me off."
    mc "I know people like that."
    mc "It takes a lot of effort to find friends who don't judge, much less who are into it, too."
    mc "But, I gotta ask..."
    mc "If you're so worried about being judged by your friends, why keep this collection in the clubroom?"
    mc "You'd think something as valuable as a comic collection would be kept at home anyway."
    n "Yeah, right."
    n "I can't keep my collection in my room."
    n "I don't even know what my mom would do if she found out I have them."
    "I furrow my brows a little."
    "His mom must {i}really{/i} hate manga..."
    n "It's safe here in the clubroom."
    n "Except when Mateo is being an arrogant jerk about it."
    n "Sometimes..."
    n "I want to punch him in the face."
    mc "Hehe...ditto on that."
    mc "But hey, at least you get to share your comics with me."
    mc "And you can rest assured I won't judge."
    hide n_cg1_exp3
    n "Yeah."
    n "That's true."
    n "Thanks, [player]."
    show n_cg1_exp1 at cgfade
    n "After all, we comic book-reading, video game-playing losers need to stick together, right?"
    mc "Loser? Hey, speak for yourself!"
    n "Hahaha!"
    mc "Jeez."
    mc "Are we gonna keep reading or what?"
    hide n_cg1_exp1
    show n_cg1_exp2 at cgfade
    n "Yeah, yeah..."
    "I flip the page."
    hide n_cg1_exp2
    show n_cg1_exp1 at cgfade
    "Natsuko suddenly bursts out laughing."
    "Right in my ear."
    "It kinda startles me."
    n "Ahahahaha! I totally forgot that happens!"
    "He leans over and points to a panel."
    n "Moji is my favorite character!"
    n "He's the comic relief but you always kinda feel bad laughing at him because of how unlucky he is."
    n "It gets especially bad when..."
    hide n_cg1_exp1
    show n_cg1_exp3 at cgfade
    n "Uh...hmm...maybe I shouldn't be talking about that."
    show n_cg1_exp2 at cgfade
    n "Just keep reading!"
    n "You'll see."

    scene bg club_day
    with dissolve_cg
    "Natsuko's voice sparkles with excitement, but he explains everything in a surprisingly slow and detailed manner."
    "It's a stark contrast from his usual fast-talking, flippant behavior."
    "But, if he's not used to sharing his comics with his friends, I can understand his eagerness."
    "It's hard to put into words the feeling you get when you connect with someone like that."
    "I'm more than happy to indulge him like this though."
    "Seeing him happy makes me smile to myself."
    show mateo 4k at t11
    m "Alright, guys!"
    mc "Hmm?"
    m 6a "Are you all ready with today's poems?"
    show natsuko at f22
    show mateo at t21
    n 6e "Oh, come on!"
    n "Are you serious?"
    n 7r "You have the worst timing!"
    show mateo at f21
    show natsuko at t22
    m 1t "Well, sorry to break up your little love-in over there."
    m 1x "But I need to make sure we have enough time."
    show mateo 1a
    mc "Love-in?"
    "Sitting so close to Natsuko wasn't bothering me before."
    "But, having Mateo point it out so bluntly makes it feel a little embarrassing."
    "I hastily jump to my feet."
    show natsuko 7f
    "Natsuko growls at Mateo as he slowly rises, gripping the book tightly."
    hide mateo
    show natsuko at t11
    mc "Alright, I guess we'll stop there for now."
    show natsuko 1s
    "Natsuko suddenly thrusts the book at me."
    mc "...?"
    n 1c "What...you think we're just gonna stop in the middle?"
    n "Don't you want to know what happens?"
    mc "Well...yeah, but..."
    n 1d "Just take it home with you and finish reading it tonight."
    mc "You're...okay with that?"
    "I say that mostly because I really, {i}really{/i} don't want to spend my spare time reading this."
    n 3z "Of course I am!"
    n 3l "I trust you won't destroy it."
    n 5c "Please don't, by the way."
    n 3k "Besides, it would take forever to read if you didn't take it home."
    n 1l "Just finish it tonight so we can start the next one tomorrow."
    n 3w "And I cannot stress this enough-- don't destroy it!"
    mc "By tomorrow? Uh, alright."
    hide natsuko
    "Well, it looks like I'm stuck reading this."
    "It'll cost me a few hours of game time."
    "But I suppose it's a necessary sacrifice to make in exchange for seeing Natsuko's enthusiastic face."
    "I stand up and return to where I left my stuff."
    "I slip the book into my bag."
    return

label natsuki_exclusive_2:
    scene bg club_day
    with dissolve_scene_half
    play music t6 fadeout 1

    show natsuko 1e at f11
    n "Hey!"
    n "Did you finish that manga last night?"
    show natsuko 1g at f11
    mc "...What manga?"
    n 1f "...What do you mean, 'what manga?'"
    n "The manga we read together yesterday that I gave you to take home and finish."
    "I shrug."
    mc "No idea what you're talking about."
    show natsuko 1c at f11
    "The color drains from Natsuko's face."
    n 1f "You know exactly what I'm talking about!!"
    n "You took it home with you to read last night, now where is it?!"
    mc "Oh...that manga."
    mc "Right."
    mc "I accidentally dropped it in the toilet."
    mc "You can have it back, but it's kinda gross..."
    n 1o "GGGgggaAAAaaaaAAAHHHhhh!!!"
    n "Are you serious?!?!"
    "Unable to keep this up any longer, I finally break and start laughing."
    mc "Ahahahaha!"
    mc "Chill out!"
    mc "I'm only joking!"
    show natsuko 1w at f11
    "Natsuko gives a massive sigh when I pull the manga volume out of my bag, unharmed."
    "I smirk."
    show natsuko 1x at f11
    mc "Whoa, time for us to hang ten, bruh."
    mc "Looks like that wave of relief is back!"
    n 1r "Oh shut up, you troll!"
    n "You almost gave me a heart attack!"
    mc "Hey, that was a good one and you know it."
    mc "Admit it."
    n 1e "Fine, fine."
    n "It was a little funny."
    n 1v "Now, give it back!"
    "He snatches it from me and promptly begins to inspect it."
    "He gives another sigh when he discovers it is in the same condition it was in when he gave it to me."
    mc "It's still in one piece."
    mc "I'm not careless, you know."
    n 1g "I'm just making sure."
    n "Can you blame me for being paranoid?"
    n "I don't just give people my comics every day."
    n "Anyway...let's put this one back and grab the next one."
    show bg closet
    with dissolve_scene_half
    "Natsuko and I head to the closet."
    n "I'm excited for you to tell me what you think so far."
    n "Where'd this volume leave off again?"
    n "I forgot..."
    mc "Right."
    mc "So, it left off where Mochi and Aki found..."
    n "Son of a..."
    show natsuko 1f at f11
    n "Mateo, did you move my stuff again?"
    show natsuko 1i at f11
    "Natsuko's voice resonates out of the closet."
    "I peer inside."
    "All of his books are lined up on the top shelf."

    m "I had to."
    m "The teacher got mad at me for taking up so much space in the closet."
    m "So I cleaned up a bit and moved some stuff around."
    n 1w "Ah! I see!"
    n 1x "And what part of your brain decided to take the shortest guy's stuff and put it on the freaking top shelf?!"
    m "Oh, stop whining."
    m "All of your crap is still there."
    m "Just get it."
    # hide_mateo
    n 1v "Ugh..."
    "I look up."
    "The top shelf is far above Natsuko's head."
    "Honestly, how does Mateo expect him to be able to reach?"
    "I watch as Natsuko makes a futile hop, trying to figure out how to reach it."
    show natsuko 1i at f11
    "He finally turns to me."
    n 3e "Will you please help me get these back down?"
    n "There's plenty of room on these shelves."
    show natsuko 1i at f11
    mc "Ah, sure."
    mc "There's a stool on the wall there."
    mc "We can use that."
    "Sure enough, there's a collapsible stool hanging on the closet wall."
    n 2z "Perfect."
    n 1l "I'll reach up there and pull them down."
    n "Then I'll hand them to you, and you can put them on this lower shelf."
    show natsuko 1j at f11
    mc "Wouldn't it be easier if I reached up there and handed them to you?"
    n 1d "Nah, it's okay."
    n "I can do it."
    hide natsuko
    "Natsuko takes the stool from the wall and unfolds it, then he hops on."
    "It's wobbly due to its collapsible design."
    "I watch anxiously."
    "I'm not much taller than him but I could definitely reach the boxes more easily."
    "Standing on the stool, Natsuko's fingertips reach the top shelf."
    "He uses his fingers to scoot one of the smaller boxes to the edge of the shelf."
    "The box suddenly tips."
    "I barely catch it before it falls to the floor."
    "The stool wobbles."
    "Losing his balance, Natsuko jumps down."
    "Thankfully, he was able to stay on his feet."
    "Having almost fell, he's clearly a bit shaken."
    "I slide the box on the lower shelf and turn to him."
    show natsuko 1g at f11
    mc "You alright?"
    n 1h "Uh...yeah."
    n "So, you know that idea you had a few minutes ago that was perfect and actually made sense?"
    n "Maybe we should just go with that."
    n "Reach the bigger boxes for me?"
    n "Pretty please?"
    "Aw."
    "Why does he have to be so cute and innocent looking?"
    "Well, he said please."
    "I smile and nod."
    mc "Of course."
    mc "But I'm not standing on that stool."
    mc "I don't trust it."
    mc "I'm using a chair instead."
    n 1e "But all the chairs in here have desks attached to them."
    n "You won't be able to fit one of those in the closet."
    mc "Hmm...Good point."
    mc "Let's see..."
    "I scan the classroom."
    mc "Aha."
    "I spot a computer chair behind the teacher's desk."
    "I roll it on its wheels back to the closet."
    n 1p "Ah...is that..."
    n "Is that safe?"
    n "It swivels and rolls."
    n "You're gonna get hurt."
    mc "Not if you hold it steady."
    mc "C'mere."
    hide natsuko
    show natsuko_bg_cgbase2
    "Natsuko comes over and grabs the back part of the chair, bracing it with his body weight."
    "I climb up on the seat and slowly stand, trying to keep my balance."
    "The chair only moves once under my weight, but Natsuko steadies it instantly."
    n "I gotcha!"
    mc "Great!"
    mc "We'll be able to do this in no time!"
    n "...Y-yeah..."
    show n_cg2_bg
    "I reach up and grab the first box of comics."
    "It's not very heavy, so I'm able to bend down and slide it onto the lower shelf."
    "I wrap my arms around the bigger box."
    "Whoa, this one is very heavy."
    mc "Oof!"
    mc "Hey, Natsu!"
    mc "This box weighs a ton!"
    mc "I won't be able to bend down to that shelf without falling."
    mc "Here."
    mc "Try to take it..."
    "I bend down as far as my strength will allow."
    "But, I don't feel Natsuko taking the weight of the box."
    mc "Hurry up, man!"
    mc "This stuff is heavy!"
    "My arms start shaking."
    "The only thing I get from Natsuko is a weird sounding grunt."
    "What the hell is he even doing?"
    mc "Hey, Natsu!"
    "I turn my head around a bit and look down."
    mc "...!"
    show natsuko_bg_cg2_exp1
    "I see Natsuko - eyes wide, cheeks red, and mouth agape - looking right up my skirt!"
    mc "Guh!"
    "Crap!"
    "I forgot I was still in school uniform!"
    "And while I usually keep my blazer tied around my waist as a 'shield', a teacher scolded me today and I was forced to wear it normally."
    "There's no doubt, he can see everything!"
    "I'd have never asked him to do this if I had remembered just what the hell I was wearing."
    mc "Hey, hey, hey!!!"
    mc "What do you think you're doing down there!?!"
    mc "Stop it!"
    "Finally snapping out of it, Natsuko suddenly realizes what he's just been caught doing."
    n "Ack!"
    n "I'm sorry! I'm sorry! I'm sorry!"
    n "I won't look!"
    show natsuko_bg_cg2_exp2
    "Natsuko turns away and covers his face with both hands, letting go of the chair."
    "It instantly starts to swivel and roll."
    mc "KYA!"
    mc "Natsu, grab the chair!"
    n "I'm sorry!"
    n "I didn't mean to look!"
    mc "Dude, just grab the chair!"
    n "I'm sorry!"
    n "I wanna help..."
    show natsuko_bg_cg2_exp3
    "He must've uncovered his eyes for a split second, because I hear him exclaim again."
    n "Oh, God!"
    n "I'm sorry!"
    n "I looked again!"
    mc "I don't care anymore!"
    mc "Just grab the chair!"
    n "I'm trying!"
    "I briefly notice Natsuko blindly grabbing at the air around the chair."
    "He can't bring himself to open his eyes long enough to stop it from moving."
    mc "AAAaaaaHHHhhhh!"
    n "[player]!"
    n "I've got you!"
    "The chair finally rolls out from under me."
    "Frantically, Natsuko tries to catch me."
    "The box topples out of my hands, and the books go flying."
    show black:
        alpha 0
        0.10
        linear 0.10 alpha 1
    $ pause(0.20)
    stop music
    play sound "mod_assets/audio/fall3.wav"
    "I slowly come to my senses."
    show bg closet
    "I sit up, pressing my arm down into what I think at first to be the floor beneath me."
    n "Ghk!"
    "I hear an exasperated grunt."
    "I look down to realize it's not the floor I'm sitting on."
    "I glare at Natsuko momentarily before grabbing him by the lapels of his blazer and jerking his upper-half up off the ground."
    show natsuko 3h at f11
    "He looks nervously into my eyes, his face still blazing red."
    mc "Natsu...when I tell you to grab the chair..."
    mc "YOU GRAB THE FRIGGIN' CHAIR!"
    "I shake him back and forth with each syllable."
    n 3p "AH-ah-ACK!"
    n "I'm sorry!"
    "He manages to whine pathetically between each shake."
    "I release my grip, dropping him back on the floor."
    "Then, I pound my fist into his chest."
    n 3v "Oomph!"
    mc "And that's for being a pervert!"
    "I place both hands on his chest and press my body weight against them, hoisting myself up."
    "Natsuko gives another groan as I step on him on my way to the nearest desk, where I drop myself in the seat."
    scene bg club_day
    show mateo 1g at f11
    m "Everything alright over here?"
    m "I thought I heard something."
    mc "Everything is peachy keen!"
    "I practically scream the last part in rage."
    "I stand up from the desk, even though my legs are now as wobbly as that stool."
    mc "Next time the teacher asks you to clean the closet, leave Natsu's stuff on the middle shelf from now on!"
    mc "Unless it's your desire to kill off your club members one by one!"
    m 1q "Jeez."
    m "You sure do like to exaggerate things, don't you, [player]?"
    mc "Spoken like someone who didn't see me plummet face-first to the floor!"
    show mateo 1c at f11
    "Mateo leans over and inspects my face very closely."
    m 2n "Well, you certainly don't look like you've damaged that pretty little face of yours."
    m 1j "So, why worry?"
    "I blush intensely as Mateo gives an amused chuckle before returning to the front of the room."
    hide mateo
    "The compliment catches me so off-guard that I forget to mention Natsuko's little stunt."
    "I look down at him."
    show natsuko 1g at f11
    "He's still laying on his back on the floor, staring forlornly at the ceiling."
    "I gingerly approach him and kneel down."
    show natsuko 1q at f11
    "He turns his head the other way."
    n "Thanks."
    n "For not telling Mateo, I mean."
    n "I...I really am sorry, you know."
    mc "Yeah, well..."
    mc "You're lucky I didn't say anything."
    mc "You try to pull that crap again and I'll..."
    mc "Oh no!!"
    "I quickly reach over and pick up one of the books that's scattered on the floor."
    "There's a long diagonal crease on one of the pages."
    "I desperately try to smooth it out."
    mc "Crap...it must've landed on the page!"
    "I try a bit more to fix the crease, but I can't get it out."
    show natsuko 1a at f11
    "Suddenly, Natsuko reaches over and takes my wrist gently."
    n 1aa "Hey..."
    n "It's okay."
    n "Don't worry about it."
    "His voice is calm and quiet."
    "It somehow sounds deeper than usual."
    mc "But...it's..."
    mc "Your childhood."
    "He chuckles sadly and looks down."
    n 1d "Yeah, well..."
    n 3ac "I never said it was the best childhood..."
    "He seems so distant all of a sudden."
    mc "Natsu..."
    mc "This isn't about the manga, is it?"
    n "..."
    "Still on the floor, he curls up on his side and turns away from me completely."
    mc "Anything I could do to help?"
    "Natsuko shakes his head."
    mc "Do you want to talk about it?"
    n 3q "..."
    n "Every day..."
    n "It's just...the same thing."
    n "I just..."
    n "I just wanna come to the club and..."
    n "...I just wanna be..."
    show natsuko 1u at f11
    "He falls silent."
    "I stare helplessly."
    "Whatever anger I was feeling regarding his little peep-show has dissipated."
    "I want to talk to him about whatever problems he may be having..."
    "But I can't pry very well if he's not ready to open up."
    "I decide to do the only thing I can right now."
    mc "Well...I'll get these comics and manga organized and moved for you."
    "I grab Volume 2 of Kaptain Kid and set it aside."
    mc "Except this one."
    mc "We'll get started on it as soon as I'm done."
    mc "Maybe that'll help make your day a little better."
    "I start collecting the books and putting them with their respective sets."
    "As I reach for one, Natsuko reaches out and gently takes it first."
    n 3t "You're..."
    n "You're really nice to me..."
    n "Thank you for that."
    n "I...I'm not used to someone being nice to me."
    n "I...I appreciate it."
    mc "I have a lot of respect for you."
    mc "Remember, there's no height limit on being a cool and interesting person."
    show natsuko 3af at f11
    "Natsuko smiles sadly."
    "I don't know what might have happened to him today, but helping boost his self esteem is the least I can do."
    "The next couple of minutes are quiet as we begin to gather the scattered books."
    "We place them in the correct order."
    "We hoist the box together and set it on a shelf Natsuko can comfortably reach."
    "I get up the courage to stand on the wobbly stool and get the rest of the boxes down."
    mc "Alright. That should do it."
    "I hop off the stool."
    n 1a "Thanks again, [player]."
    mc "Any time."
    "Natsuko is holding the volume I set aside."
    n 1ah "Shall we?"
    "He smiles a little."
    "Looks like he's starting to cheer up already."
    mc "Alright, I'm ready."
    hide natsuko
    "We sit in the same spot as last time, and I open the second volume."
    "Natsuko's mood continues to improve as he laughs and points things out to me."
    "He's surprisingly sharp, making note of a lot of subtle repeated jokes and background elements."
    "In the end, I'm pretty impressed with how well everything ties up in this story, despite Natsuko saying the story doesn't hold up."
    "I guess he has good taste after all."
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
