label ch4_main:
    scene bg Fmbedroom
    with dissolve_scene_full
    play music t6
    "It's already Sunday." 
    if ch4_scene == "yuri":
        "I've been getting increasingly anxious about Yuuri's upcoming visit." 
        "I keep telling myself there's no reason to be nervous, but it hasn't helped much." 
        "Yuuri is clearly an introvert and a gentleman, but I think under it all, he's also a very intimate person."
        "He seems so uptight around the other guys. I'm hoping he relaxes and opens up a little more when it's just the two of us." 
        "We have been texting occasionally." 
        "He was a bit apprehensive at first but it wasn't long before I was already learning more about him." 
        "But putting Yuuri aside..." 
        "I haven't heard much of anything from Satori the past couple of days." 
        "I've called, texted and even went to his house." 
        "But each time I checked in on him, he's been passed out face down in his pillow." 
        "His \"bad day\" seems to be lingering and I don't know why." 
        "Between him and Yuuri's visit, my anxiety is through the roof." 
        "I look at the clock." 
        "Yuuri will be here in about 2 hours."
    else:
        "I've been getting increasingly anxious about Natsuko's upcoming visit." 
        "I keep telling myself there's no reason to be nervous, but it hasn't helped much." 
        "I wonder how different he's going to be when it's just the two of us?"
        "He seemed to be more openly flirty after the others left the clubroom." 
        "Meanwhile, he's been texting me a lot." 
        "We had sent each other one to double check, but it turned into a whole conversation." 
        "I'm a little surprised by how sweet he is on the phone." 
        "He's almost a different person." 
        "He's still quite flirty, but that's to be expected." 
        "But putting Natsuko aside..."
        "I haven't heard much of anything from Satori the past couple of days." 
        "I've called, texted and even went to his house." 
        "But each time I checked in on him, he's been passed out face down in his pillow." 
        "His \"bad day\" seems to be lingering and I don't know why." 
        "Between him and Natsuko's visit, my anxiety is through the roof." 
        "I look at the clock." 
        "Natsuko will be here in about 2 hours." 
    "Time for a quick, last-minute clean up." 
    "I get to work shoving clothes in the closet and papers with doodles on them into my desk drawers." 
    "Can't have my book bag just lying around, I suppose." 
    "I grab it so I can put that in the closet as well." 
    "The strap suddenly snaps and it falls to the ground, spilling everything out." 
    "I let out a long, exasperated sigh."
    mc "Awesome."
    "I drop to my knees and begin scooping up my various papers and text books." 
    "As I do so, I dismissively look through some of the papers." 
    "Let's see." 
    "Failed test..." 
    "Detention slip..." 
    "Notes I never used..." 
    "Countless doodles..." 
    "Another detention slip..." 
    "...?" 
    "I suddenly come across what appears to be a prescription bag with a couple of pill bottles inside." 
    mc "What the..." 
    "This isn't mine..."
    "I look it over and check for a name." 
    mc "...!"
    mc "S-Satori?!"
    "This must have been put into my bag by mistake when we took that trip down the stairs a few days ago." 
    "Since when is he on medication?" 
    "I pull out the bottles and scan their labels carefully."
    "I grab my phone and look up both medications." 
    "..."
    "..."
    mc "Whoa...what?! How?! Since when?!"
    "I hastily finish shoving everything else in my closet." 
    if ch4_scene == "yuri":
        "I don't have much time before Yuuri comes over." 
    else:
        "I don't have much time before Natsuko comes over." 
    "But despite this, I race out the door." 
    "Whether Satori likes it or not, I'm coming over and we are going to talk about this."

    scene bg residential_day
    with wipeleft_scene
    stop music fadeout 2.0
    "I don't even bother to text or call." 
    "I don't even knock." 
    "I just swing the door open and head inside." 
    "It's not unusual, after all." 
    "We hang out at each other's houses so often, we practically live together."
    scene black
    with wipeleft_scene
    "The house is quiet." 
    "Satori isn't anywhere on the first floor, so I head upstairs." 
    "I half expected him to come down and shoo me back out the door, but the entire house is silent." 
    "My heart races." 
    "I head up to his bedroom and gently open the door."
    scene bg satori_bedroom
    with wipeleft_scene
    show satori 11o at t11 zorder 2
    play music t9
    "I see him lying on the bed, but he promptly leaps to his feet, clearly startled by my sudden entrance."
    s 17j "Jeez, knock much?"
    "My blood pressure settles down a bit."
    show satori 11i at t11 
    "He looks tired and a bit irritated, but otherwise, okay." 
    "I quietly take a seat on the bed."
    show satori 11g at t11
    "He reluctantly sits down next to me." 
    show satori 11y at t11
    "He forces a smile." 
    "There's a moment of silence between us."
    s 12y "You didn't need to come over." 
    s 11k "I mean..." 
    s 11d "I'm happy to see you and everything..." 
    s 17g "But don't you have something more important to do today?"
    mc "..."
    mc "What do you mean?"
    if ch4_scene == "yuri":
        s 11f "Yuuri..." 
        s "You're supposed to be working with him today, aren't you?"
        mc "...How did..."
        "Satori had gone home by the time we decided that last meeting."
        "But I quickly realize how he knows."
        mc "Mateo told you, didn't he?" 
        s 11h "Of course."
        s "He's supposed to keep me up to date on the festival preparations." 
        s 11av "I'm the Vice President, after all..." 
        mc "Yeah...yeah." 
        mc "So how 'bout you?" 
        mc "You're helping him today, right?"
        s 11g "Yeah, but only online." 
        s "We don't have to meet up or anything." 
        s 11at "Anyway, I bet you're excited to be working with Yuuri, huh?"
    else:
        s 11f "Nat... You're supposed to be baking with him today, right?"
        mc "...how did you know that?"
        mc "...How did..."
        "Satori had gone home by the time we decided that last meeting."
        "But I quickly realize how he knows."
        mc "Mateo told you, didn't he?" 
        s 11h "Of course."
        s "He's supposed to keep me up to date on the festival preparations." 
        s 11av "I'm the Vice President, after all..." 
        mc "Yeah...yeah." 
        mc "So how 'bout you?" 
        mc "You're helping him today, right?"
        s 11g "Yeah, but only online." 
        s "We don't have to meet up or anything." 
        s 11at "Anyway, I bet you're excited to be baking with Nat, huh?"
    mc "Satori, I'd rather be working with you."
    show satori 11i at t11
    "Satori looks over at me briefly." 
    s "No you wouldn't." 
    if ch4_scene == "yuri":
        s 11au "I know you've wanted to be alone with Yuuri since you joined the club."
    else:
        s 11au "I know you've wanted to be alone with Nat since you joined the club."
    mc "That's not...!"
    mc "...Look, that's not what I came here to talk about." 
    mc "I'm here to talk about this."
    show satori 11o at t11
    "I hold up the bottle labeled ZYPREXA." 
    "Satori quickly snatches the bottle from my hands."
    s 11c "How the heck did you get this?!"
    mc "It was put in my backpack on accident a few days ago when we fell down the stairs."
    s 17at "Well, this explains why I've been able to sleep so well the past couple of days."
    mc "Yeah, I know."
    mc "I looked it up and saw one of the main side effects is insomnia."
    mc "Satori...how long have you been on this?"
    s 11k "..."
    s 11g "You're not gonna like the answer."
    mc "I don't care." 
    s "[player]..."
    mc "Don't '[player]' me!"
    s 17ac "Sigh. You're just gonna make me say it, aren't you?"
    mc "..."
    s 11av "Fine..."
    s "The truth is..."
    s 11k "I was diagnosed with Bipolar Disorder when I was 10 years old."
    s 17g "I've been on Zyprexa ever since."
    "The news hits me like a ton of bricks."
    "I don't even know how to respond."
    "I slowly rise to my feet, my shocked gaze locked on Satori's face."
    mc "T-t-ten?"
    s 14h "Told ya you weren't gonna like the answer..."
    mc "I..I just...I don't understand. We're best friends..."
    mc "We tell each other everything. Why wouldn't you tell me about this? Knowing I could help?"
    s 11ab "I didn't tell you because I didn't want you to worry about me." 
    s 11k "You do that a lot, you know." 
    s 11at "You spend so much time worrying about me that you don't have time to do important things."
    "I feel myself getting increasingly angrier at his words."
    mc "Of course I worry about you, you're my best friend!"
    mc "You're so important to me, I even worry about you when I watch you cross the street!"
    mc "I love you, you big stupid idiot! Why would you not tell me about this?!"
    mc "What is even the point of us being best friends if you're not gonna be open and honest with me about stuff like this?!"
    mc "God, I can't believe...you never told me..."
    s 12g "...Are you mad at me?"
    "I shake my head silently."
    mc "I just...I don't understand why you kept this from me."
    s 11av "You can never understand."
    mc "What, because you didn't want me to worry about you?"
    mc "C'mon, Satori."
    mc "That's ridiculous..."
    s 11g "To you, maybe."
    s "But having you worrying about me...and caring about me..."
    s 11h "It feels like a bat being swung against my head."
    s 11k "It's bittersweet to have anyone care about me."
    s 17h "That's why I wanted you to make friends with everyone in the club when you decided to join."
    s 15av "I figured, if I could get you to care for them, you'd stop caring about me..."
    mc "Really? Is that what you think?"
    "I walk away a few feet, staring at nothing."
    mc "You think I'm so shallow and heartless that I could just abandoned my best friend for the first guy to write me a poem?"
    mc "..."
    s 11g "..."
    "Now I feel myself becoming increasingly emotional."
    "I want to stop myself before I become irrational, but I find myself unable to curb my tongue."
    mc "Is that why you never told me about this, Satori?"
    "My voice cracks."
    mc "Am I that bad of a friend that you just felt you couldn't trust m-..."
    "Before I have a chance to finish, Satori jumps to his feet and wraps his arms around me, pulling me into an embrace."
    scene black
    with dissolve_cg
    "Tears freely begin to flow from my eyes as his embrace tightens." 
    s "Please..."
    s "Please don't do this..."
    "He begins to tremble."
    s "I...I don't want you to hurt...because of me..."
    s "I...I'm sorry I made you feel this way."
    mc "No..."
    "I wrap my arms around him in return."
    mc "I'm the one who's sorry." 
    mc "I'm so, so sorry you've been going through this for so long and I hardly even noticed." 
    mc "What kind of friend am I that I didn't even pick up on the fact that you were struggling with this?" 
    mc "How could I be so blind?"
    mc "I'm sorry, Satori..." 
    mc "I'm... I'm a terrible friend."
    s "..."
    s "No, [player]..."
    s "Don't say that." 
    "He holds me so tight against him, I can feel his heart pounding."
    "I instantly regret what I said before, as I predicted I would."
    "This isn't about me. This is about my best friend. It's my job to find out how I can help him."
    "I rest my face against his shoulder and sigh."
    s "You're the most wonderful friend anyone could ever ask for."
    s "I love you so much."
    s "That's why I didn't tell you."
    s "I don't deserve to have such an amazing and big-hearted person care about me so much."
    s "You just don't understand...how much it hurts..."
    mc "But why?"
    mc "Why do you feel so selfish and undeserving?"
    mc "The meds are working, right?"
    s "..."
    s "Yeah..."
    s "When I take them."
    scene bg satori_bedroom
    with dissolve_cg
    show satori 11k at t11
    "Satori and I release our embrace and slowly part."
    mc "What do you mean 'when you take them'?"
    "Satori shrugs indifferently."
    s 11at "I don't ALWAYS take them."
    s 17i "You read for yourself that they cause insomnia. I gotta get sleep sometime..."
    s "..."
    s 17h "So on days when I'm moodier than usual..."
    s "It's because I didn't take them, so that I could sleep."
    "I swallow nervously as I reach into my pocket and wrap my fingers around the 2nd pill bottle."
    mc "Well...I can understand that."
    mc "But, truthfully, those aren't the meds I was talking about."
    show satori 11ae at t11
    "I notice Satori's expression change as I pull the bottle labeled LITHIUM from my pocket."
    mc "I'm talking about this."
    "He backs away a couple steps."
    s 11ad "I don't need THAT stuff."
    mc "They wouldn't have prescribed it if you didn't need it, Satori."
    s 15ah "Well I don't need it, alright?"
    hide satori
    with wipeleft
    "He snaps as he crosses his arms and leans against the wall, his back turned."
    s "I'm not taking it. Period."
    "I sigh and stand up." 
    show satori 11ad at t11
    "I walk to the center of the room and stand near him."
    mc "You really need to reconsider that decision."
    s 17i "Yeah? And what makes you so sure of that?"
    mc "Because they only prescribe that stuff to people with depression..."
    mc "..."
    mc "People with..."
    mc "Suicidal thoughts."
    s 11au "There's nothing to worry about."
    s 18j "It's common for people with BPD to have bouts of depression."
    s 11at "I'm fine as long as I have the zyprexa."
    mc "It just seems weird that they'd prescribe such a serious medication made for severe depression to someone who just has 'bouts' of it..."
    s 14j "Look, they just overreacted when they prescribed it to me!"
    s 11i "I'm not gonna do anything crazy."
    s "So just drop it, okay?"
    mc "..."
    mc "'Sad Thoughts' was about your depression, wasn't it?"
    "Satori shakes his head and gives an annoyed grunt." 
    s 17j "I already told you..." 
    s "You looked too much into that poem." 
    s 11at "I'm sorry I ever wrote the stupid thing."
    mc "I'm not. I love that poem." 
    mc "It's my personal window into your mind." 
    mc "And when I look in that window and see that you have a little raincloud in your head..." 
    mc "Well, I can come in and give that raincloud a little hug." 
    mc "And make a big happy rainbow."
    s 11ap "[player], that's..." 
    s 11y "That's so corny."
    "Satori smiles a bit." 
    "Even though he's smiling, I can feel the melancholy radiating off of him." 
    mc "Satori..."
    s 11g "Yeah?"
    mc "..."
    mc "You were diagnosed with BPD when you were 10, and you said that's when they prescribed the zyprexa, right?"
    s 11b "Right."
    mc "..."
    mc "When was the lithium first prescribed to you?"
    s 11ab "..."
    s 11at "Doesn't matter."
    s 17j "I already told you I'm not taking it."
    show satori 11at at t11
    "He stubbornly walks over to his bedroom window."
    mc "Well, at least tell me what you get depressed about..."
    if ch4_scene == "yuri":
        s 11au "Yuuri's coming."
        "He cuts me off." 
        "I look down on the street and sure enough, I spot Yuuri walking towards my house carrying some bags." 
        "I completely forgot he was coming over." 
        "I look at Satori, who keeps his gaze on Yuuri below." 
    else:
        s 11au "Nat's coming."
        "He cuts me off." 
        "I look down on the street and sure enough, I spot Natsuko walking towards my house carrying some bags." 
        "I completely forgot he was coming over." 
        "I look at Satori, who keeps his gaze on Natsuko below."
    mc "Satori...if you need me today, I'll cancel.."
    s 13m "Don't do that, [player]!"
    "I jump back, startled." 
    show satori 11e at t11
    "Satori immediately realizes the effect of his outburst and shrinks back a little."
    s 12g "I'm sorry..."
    s "It's just..."
    s 17h "I'm sure he's been looking forward to this all weekend."
    s "Please don't ruin that for him."
    s 15d "Besides, I'll be busy today." 
    s "I still have some festival stuff to talk about with Mateo."
    mc "...Alright."
    "I get up and head for the door." 
    "I stop and look back at Satori, still standing in front of the window with his back to me."
    if ch4_scene == "yuri":
        mc "If, um...if you finish early with helping Mateo, feel free to come over to help me and Yuuri with the decorations."
    else:
        mc "If, um...if you finish early with helping Mateo, feel free to come over to help me and Natsu with the donuts..."
    "Satori merely shakes his head."
    s 11g "No, thanks." 
    s "I'll see him tomorrow at the festival." 
    s 11d "You two have fun."
    mc "Okay."
    mc "We'll have a good time at the festival, though, right?"
    mc "I mean..." 
    mc "If you're okay with it, I'd like to spend the day with you." 
    mc "Would... Would that be alright?"
    "Satori turns his head slightly."
    show satori 11k at t11
    "I was hoping for an excited grin, but instead, he gives me a sad smile." 
    "After a moment, he nods."
    s 17d "Of course, if that's what you want." 
    s 11k "But I wish you'd consider spending your time with everyone else."
    mc "I will." 
    mc "I plan on having fun with all my friends." 
    mc "The friends I wouldn't have if it weren't for you." 
    mc "But no matter how many new friends I make, I'll never be far from your side." 
    mc "Because we're best friends." 
    show satori 11y at t11
    mc "And you're stuck with me no matter what."
    show satori 11q at t11
    "Finally, I manage a smile out of Satori." 
    "There's real happiness in it this time."
    show satori 11d at t11 
    "It quickly fades, but it gives me hope that I can bring it back out again." 
    "I just wish he would tell me more about his depression so maybe I can help him."
    "I guess I'll just have to be patient and hope he eventually decides to confide in me."
    "I step out the door and grab the knob."
    mc "If you change your mind, feel free to drop by."
    "Satori gives me one more melancholy smile and nod before I slowly close the bedroom door behind me."
    call expression "ch4_exclusive_" + ch4_scene
    call ch4_end
    return

label ch4_end:
    scene bg Fmbedroom
    with wipeleft_scene
    stop music fadeout 2.0
    show satori 11av at t11
    "Once we're in my room, I shut the door and take a seat on my bed." 
    "I feel anxious over what Satori might tell me." 
    mc "So, um...what's on your mind?"
    s "..." 
    s 11k "I've been thinking about what you said this morning." 
    s 17k "About how we're best friends and we trust each other with everything." 
    s "And..." 
    s "Well..." 
    s 11f "You're right."
    s "You deserve to know what's going on."
    "I smile a little in relief."
    "Looks like he's going to open up to me after all." 
    "I lean forward a bit, my full attention on Satori."
    mc "I'm all ears."
    mc "Tell me everything, Satori." 
    mc "The more I know, the more I can do to help."
    s 11k "Right..."
    s "..."
    s 17h "The Lithium was prescribed to me last year..."
    s 15av "...After I was diagnosed with chronic depression."
    "I sigh and nod."
    "I knew it."
    mc "I see..."
    mc "Do you know what caused you to become depressed?"
    "He nods."
    s 11f "Yeah. I do."
    s 11h "It was because I came to a realization."
    mc "What did you realize?"
    "He takes a deep breath."
    s 11ax "I realized...I have...feelings..."
    play music t9
    s "Selfish, selfish feelings..."
    mc "...?"
    mc "Selfish feelings?"
    mc "I...I don't think I understand..."
    s 11ay "It's easy, [player]."
    s "I discovered..."
    s 15az "...That I hate the idea of you getting a...a boyfriend."
    s 15an "Isn't that disgusting of me?"
    s 15w "To act like you're a shiny toy that I want only for myself?" 
    s 11v "I mean..."
    s "You're such an amazing, smart, funny person."
    s 17e "Everyone deserves to be around you."
    s 15ax "And even knowing that..."
    s 15aw "I still hate the thought of you being...with someone else."
    s 15ay "I realized...someone as selfish as me doesn't deserve to be around someone as wonderful as you."
    s 11av "That's why I didn't want to take the Lithium."
    s 11aw "Don't you see? I deserve to feel this way."
    s "I deserve to hurt..."
    s "I deserve...to be punished for being weak and selfish."
    s 11v "Why do you think I never personally invited you to the club?"
    s 11w "I didn't want them to be around you..."
    s 13w "To see how beautiful and amazing you are."
    s 15an "I knew they'd be head over heels for you."
    s 12aw "I mean...sure, I was excited to have you visit."
    s 17v "And after you decided to join, I figured it'd be a great chance for us to get to spend even more time together."
    s 15aw "But...on our way home that day...you...you said you liked them..."
    s "You wanted them to...like you."
    s 15v "And...I just want you to be happy."
    s 15ax "..."
    s 15ay "Agreeing to help you...giving you advice on how to impress them...it..."
    s 15az "It felt like my heart being ripped in half..."
    s 15an "But...it was a bittersweet blessing in disguise, you know?"
    s 15v "I figured if you got closer to one of them, you'd forget about me."
    s "You wouldn't have me to hold you back."
    s 15aw "If you stopped caring about me..."
    s "You wouldn't care if anything happened to me..."
    mc "Satori..."
    s 15w "Hold on!"
    s 15u "There's something else..." 
    s 11v "I realized that the closer you got to each of them..." 
    s 13an "The more it felt like a spear going through my heart." 
    s "[player]..." 
    s "Just the thought of you doing anything...romantic...with one of them..."
    s 13am "It hurts so much!" 
    s "It makes me sad and angry; at them and at myself!" 
    s 13az "The thought of you with anyone else but me makes me want to die!"
    mc "Satori, don't say things like that!"
    s 13w "I can't help it, [player]!" 
    s 13an "The truth is..." 
    s 13v "I...I love you." 
    mc "..."
    s "Those are my true feelings." 
    s 15v "I've always loved you."
    s 11aw "And...starting last year..."
    s 11v "I realized...I'm in love with you." 
    s "I mean..."
    s 17v "We've been saying it to each other for years." 
    s "But I don't just say it to you because it's a thing to say."
    s 15v "I mean it every single time."
    "Satori suddenly steps closer to me, gently taking my hands in his own."
    s 11u "What about you?"
    s "Do you mean it, [player]?"
    s 11v "Do you feel anything at all when you tell me that you love me?"
    "I meet Satori's gaze." 
    "I owe it to my best friend to be completely honest with him." 
    mc "Satori, listen to me." 
    menu:
        mc "Every time I tell you that I love you, I mean..."
        "I'm in Love with You":
            $ sayori_confess = True
            call ch4_end_yes
        "I Love You Like a Brother":
            $ sayori_confess = False
            call ch4_end_no
    return

label ch4_end_yes:
    mc "I'm in love with you." 
    show satori 11e at t11
    mc "I've felt this way for a while too."
    mc "I mean...of course I mean it when I say it." 
    mc "And if we both love each other this much, well..." 
    mc "There's no point in worrying about me doing anything with the others!" 
    mc "These past few days in the club have been amazing." 
    mc "I've made some great new friends because of you." 
    mc "But being in the club has also made me realize something else." 
    mc "Satori...you're my reason for waking up in the morning."
    mc "Not just because of school." 
    mc "But because I want nothing more than to have yours be the first face I see every day." 
    mc "I've had so much fun in the club because you and I get to spend more time together than ever before." 
    mc "Whether or not I've had fun with the others is irrelevant." 
    mc "The only thing that matters to me is getting to spend every day with you."
    "Satori stares at me in bewilderment."
    "I expect him to hug me, but that doesn't seem to be the case."
    s "...[player]..." 
    s 11k "For years, I've dreamed of hearing you say that you feel the same way about me as I feel about you." 
    s "This is supposed to be the happiest moment in my life." 
    mc "..."
    mc "Supposed to be?"
    mc "Satori..."
    show satori 15ao at t11
    "Satori's look of shock suddenly transforms into one of frustration."
    s 13ah "No!"
    s 13am "What have I done?"
    s "Confess to you..."
    s "I shouldn't have confessed to you!"
    s 13an "That's not why I came here!"
    s 13ao "Why did I do that?!"
    s "Why did I make the stupid mistake of expressing my feelings!?"
    s 13ak "Ugh, I just made everything WORSE!"
    mc "Satori, what're you..."
    s 13ah "NO!"
    "He slams his fist against my wall."
    s 13az "WHY CAN'T I STOP BEING SELFISH?!"
    mc "Would you calm down!?"
    show satori 13an at t11
    mc "You're not being selfish!"
    mc "What's wrong with me wanting to be with you?"
    mc "Isn't that what you want?"
    s 13ao "Yes...No!..."
    s 13am "I DON'T KNOW!!!"
    mc "Well, Jesus, dude!"
    mc "I hate to have to point this out, but..."
    mc "Maybe you'll think a little more clearly if you took your medication!"
    show satori 13v at t11
    mc "And I mean both of them!"
    mc "Because it's really hard for me to try to help you when you're warping the meaning of your feelings in a way that makes you sound like you're being the bad guy here!"
    mc "And you're not!"
    mc "You're a wonderful person who I love with all my heart and I just want you to take care of yourself!"
    s 13ak "...I just want YOU to hate me!"
    s "Why is that so hard?"
    mc "I just want YOU to TAKE YOUR MEDS!!"
    mc "WHY IS THAT SO HARD!?"
    "We stare each other down with annoyed scowls."
    show satori 13af
    "I didn't mean to yell at him."
    "I'm just frustrated by his inability to think rationally right now, even though it's not really his fault."
    "I can imagine he's not the only one with these problems who doesn't like taking his meds..."
    s 11ao "..."
    s 11ac "You...want me to take them that bad?"
    s 11at "Fine."
    s 11au "I will."
    mc "..."
    mc "Seriously?"
    mc "You're not just trying to placate me?"
    s 11av "No."
    s "I'm being 100\% honest with you."
    s 11k "When I go home...I will take my meds."
    mc "The lithium, too?"
    s 11ax "..."
    s 11ay "Yeah."
    mc "...Alright."
    mc "Thank you."
    mc "I know the zyprexa messes with your sleep...but...try to take some of that too, okay?"
    s 11k "Sure thing."
    "I nod, eying him curiously."
    mc "Okay, then."
    mc "I appreciate you doing that for me, Satori."
    mc "The meds really will help, you know."
    s 11ay "..."
    s "They sure will." 
    "His anger fades into bland complacence."
    "It has me a little worried about him being alone tonight."
    mc "...Do you wanna stay over for a little bit?"
    mc "Play a few games?"
    show satori 11av at t11
    "Satori stares off in a random direction and gives an empty smile."
    s 11d "No, thanks."
    s "I think I'm gonna turn in early."
    mc "Alright. Good idea."
    mc "We'll both wanna be up early tomorrow anyway, right?"
    s 11k "...Right."
    hide satori
    "He starts to leave."
    "I still feel uneasy with his emotionless responses."
    mc "Satori..."
    "He stops in front of my bedroom door, though he doesn't turn to face me."
    "I walk over and stand between him and the door."
    "He keeps his head down."
    "Slowly, I lean in and embrace him."
    scene s_cg3_base
    with dissolve_cg
    "He refrains from hugging me back."
    "Undeterred, I pull him closer."
    show s_cg3_exp1 at cgfade
    "We stand in silence for a few moments before I finally feel his muscles relax a bit."
    "A few more moments pass and his arms slowly wrap around me in return."
    show s_cg3_exp2 at cgfade
    s "I just...I just want the raincloud to go away..."
    "He whispers this in a trembling voice."
    "I lean my head against his chest."
    show s_cg3_exp3 at cgfade
    mc "It will."
    mc "It might take a little while, but the sunshine will come back and chase that old raincloud away."
    mc "I'll make sure of it."
    mc "You trust me, right?"
    s "...Yeah."
    scene bg Fmbedroom
    with dissolve_cg
    show satori 11aw at t11
    "We slowly part."
    mc "Are you sure you're gonna be okay tonight?"
    s 11v "...Yeah. I'm sure."
    mc "Okay."
    mc "We're gonna have lots of fun at the festival, right?"
    s "...Of course."
    s 11t "It'll be great."
    show satori at thide
    hide satori
    "He gives me another sad smile before quietly leaving the room."
    "I hear him trot down the stairs and leave through the front door." 
    "I watch from my window as he heads down the street to his house."
    "I can't help but feel a sense of uneasiness." 
    "What if my suggestion for him to take his meds backfires and it ends up making him worse?"
    "What if I should be doing something more, or something different?" 
    "I know these thoughts will continue to plague me until I see if my suggestion works or not."
    "If he takes my advice, I should notice any changes in his behavior by tomorrow." 
    "I hope he'll be back to his normal, cheerful self by then."
    "Either way, I'm willing to do whatever it takes to give Satori a happy life with me."
    $ persistent.clear[8] = True
    $ renpy.save_persistent()
    # $ if all(clear for clear in persistent.clear): persistent.clearall = True
    # if persistent.clearall:
    #     $ persistent.efuse = True
    # else:
    #     $ persistent.efuse = False
    return

label ch4_end_no:
    show satori 11v at t11
    mc "...I love you like a brother." 
    show satori 11e at t11
    mc "I'm comfortable doing everything with you." 
    mc "I can tell you anything and everything." 
    mc "I mean, I know we're not really siblings." 
    mc "But...we might as well be, you know?" 
    show satori 11aw at t11
    mc "And there's nothing wrong with that."
    mc "I'll always love you. Nothing is gonna change that."
    mc "I'll be here for you whenever you need me."
    mc "No matter what..."
    mc "You'll always be my buddy."
    s 11az "I... I see..."
    "Satori's eyes fill with tears." 
    "He slowly backs away from me."
    s 11v "So this is what it feels like to be stabbed in the chest..."
    mc "...Satori..."
    s 11u "No. You're 100\% right, [player]." 
    s 15aw "We...we're better off keeping things the way they've always been." 
    s "I mean...everything was perfect before I accidentally showed my feelings." 
    s 15az "We wouldn't even be having this conversation right now if it hadn't been for that stupid, selfish mistake."
    "Satori has a hard time keeping his voice steady."
    s 15v "I trust you to know what's best for me." 
    s "Keeping things the way they've always been." 
    s 11aw "It's what I want too..."
    "He looks away, tears streaming down his face."
    s 11ay "Really...this couldn't have turned out better..."
    "I swallow nervously, realizing that me turning down his confession could seriously impact his depression."
    mc "Satori..."
    mc "I...I know you don't want to hear this..."
    mc "But...now that you have the lithium on hand...please consider taking it."
    "He gives an emotionless chuckle."
    s 11t "It wouldn't have been an issue either way."
    s "I have tons of it stockpiled in my medicine cabinet."
    mc "Well...it would make me really happy if you started taking it."
    mc "I'm sure it'll help you a lot..."
    s 11y "..."
    s "You know what?"
    s 11t "Maybe I will."
    mc "Really?"
    s 11y "..."
    s 11t "Sure."
    s "If it'll make you happy..."
    mc "It will."
    "Satori passively nods."
    s "Alright."
    s "When I go home, I'll take my meds."
    mc "The lithium, too?"
    s "...Of course."
    mc "Thank you."
    mc "And in return, I'll make sure you have a lot of fun at the festival tomorrow."
    mc "Sound good?"
    s 11aw "..."
    s 11t "Yeah."
    s 17t "I'm sure it'll be fun." 
    show satori at thide
    hide satori
    "Satori gives me one more sad smile as he leaves my room."
    "I listen as he wordlessly descends the stairs and walks out the front door." 
    "I look out my window and watch him slowly cross the street and make his way to his house." 
    "I can't help but feel a sense of uneasiness." 
    "What if my suggestion for him to take his meds backfires and it ends up making him worse?"
    "What if I should be doing something more, or something different?" 
    "I know these thoughts will continue to plague me until I see if my suggestion works or not."
    "If he takes my advice, I should notice any changes in his behavior by tomorrow." 
    "I hope he'll be back to his normal, cheerful self by then."
    "Either way, I'm willing to do whatever it takes to help Satori get through this difficult time." 
    return

label ch4_exclusive_natsuki:
    stop music fadeout 2.0
    scene bg residential_day
    with wipeleft_scene
    play audio t6
    "I exit Satori's house." 
    "On the way home, I still find myself feeling uneasy." 
    "I try to focus my thoughts on Natsuko, convincing myself that tomorrow will be a better day for everyone, including Satori." 
    "I follow Natsuko, staying about a hundred feet behind." 
    "I'm sure he hasn't spotted me." 
    "As he turns to walk up my driveway, I see him take out his phone." 
    "He disappears from my view as he heads up to the house, obscured by the bushes on the corner of the driveway." 
    "Within moments, I hear the musical tone of my phone letting me know I have a new text." 
    "It's from Natsuko, saying he's outside my door." 
    "I decide it'd be more fun to sneak up on him." 
    "I round the corner and slink up the driveway." 
    "But as my door comes into view, I only see the bags he was carrying sitting on the patio." 
    "I stare at the lone bags for a moment." 
    "Where the hell did he go?"
    show natsuko 12z at t11
    n "Gotcha!"
    mc "Kya!!"
    "I practically leap out of my pants as Natsuko suddenly appears behind me and gives my ribcage a little tickle." 
    "I'm pretty sure my soul left my body there for a moment." 
    n 12ap "Hahaha!" 
    n "You should see your face!" 
    n 10l "Man, I really gave you a scare, didn't I?"
    mc "I'd stuff you in the microwave for pulling that little stunt!" 
    mc "But then I'd have no one here to make donuts." 
    mc "And I wasn't scared, by the way." 
    mc "I was mildly alarmed." 
    n 13y "Yeah, right!" 
    n "You're just mad because you wanted to sneak up on me and I beat you to the punch."
    mc "..."
    mc "Touche."
    "Satisfied with himself, Natsuko struts proudly to the door and gathers the bags."
    n 9l "Let's head inside." 
    n 9a "We have a lot of work to do."
    scene bg kitchen
    with wipeleft_scene
    mc "I see you brought a lot of stuff."
    "Natsuko carries in three large bags that I'm assuming are filled with baking supplies. He places them on the counter."
    show natsuko 8a at t11
    n "Well, I didn't want to come all the way down here just to find out your kitchen isn't equipped for the job." 
    n 8d "Did you buy everything I asked you to?"
    mc "Yep."
    "Natsuko messaged me yesterday asking me to pick up a bunch of ingredients if I didn't already have them at home." 
    n 9z "Great!" 
    n "Glad I could count on you to do your part!"
    mc "Oh, of course." 
    mc "I take donuts very seriously."
    n 10d "I sure hope so." 
    n "Can't have you ruining my recipe."
    mc "YOUR recipe, huh?" 
    mc "So you DO bake often..."
    show natsuko 12p at t11
    "Realizing his unintentional confession, Natsuko's face turns bright red."
    n 12o "Ack!" 
    n 12r "N-n-n..." 
    n 12s "That's not..." 
    n 12s "Ah...!"
    mc "Calm down, Natsu." 
    mc "I think it's awesome that you make such tasty treats." 
    mc "It's nothing to be embarrassed about." 
    mc "If anything, it makes me think even more highly of you." 
    mc "I mean..." 
    mc "I don't expect any less from a pro!"
    n 12u "That's..."  
    n 12t "I'm glad to hear you say that." 
    n 13u "I just don't..." 
    n 13n "I don't want the other guys to know." 
    n 13q "They'll just make fun of me about it and piss me off."
    mc "Then I guess they won't be partaking in your delicious donuts, will they?" 
    mc "And whose loss is that?"
    n 13at "Ehehe..." 
    n "That's true, I guess!" 
    n 13aw "But still..." 
    n 13ax "Could you keep this between us?" 
    n 13u "It's bad enough I'm the shortest one in the club." 
    n 13m "I don't want them to have more ammo, knowing I bake too, you know?"
    mc "No worries." 
    mc "Your secret is safe with me."
    n 10as "Thanks, [player]."
    show natsuko 12ar at t11
    "There's some silence between us when Natsuko suddenly gives me a strange look."
    mc "...Um..."
    n 12m "Ah! S-s-sorry..." 
    n 12q "It's just..." 
    n 10t "This is the first time I've seen you outside of school."  
    n 10n "You..." 
    n 10ax "You look really pretty today..."
    mc "...!" 
    mc "N-Natsu, that's..."
    "Well..." 
    "I was expecting Natsuko to act different when it was just the two of us..." 
    "But I never expected that someone who's usually so blunt and bossy could be so unbelievably charming." 
    mc "That's really nice of you to say something like that..."
    "I mean, if we're being honest here..." 
    "I think Natsuko looks pretty cute in his casual clothes too." 
    "Somehow, they make him look older than usual." 
    "He may not have Yuuri's mature build, but he's clearly not a kid either." 
    "Plenty of girls prefer the youthful boy-band look anyway." 
    n 13t "Haha! Well, let's not make a big deal out of it!" 
    n 10d "We don't need to talk about weird things just because we're not in school." 
    n 9d "Let's get started." 
    n "There's a lot for me to teach you." 
    n 9y "So be prepared to pay close attention, if at all possible." 
    n 9w "And for crying out loud..." 
    n 9b "Keep your fingers OUT of the batter!"
    "Ah, there's that attitude." 
    "I smile a bit to myself." 
    "I do like when he speaks his mind like that." 
    "It gives me license to dish it right back to him." 
    "We start pulling items out of the bags and finally get started."
    scene bg kitchen
    with wipeleft_scene
    "Before long, the entire kitchen is a mess." 
    "Spoons, dirty bowls, flour, spilled liquid and plastic bags are strewn about every counter top." 
    "Of course, about 99\% of the mess was made by me." 
    "Turns out, I suck at baking and have exhausted Natsuko at every turn." 
    "The mixer wasn't big enough to mix all the batter at once, so we had to to do it several times." 
    "I've had my hand slapped with a wooden spoon at least two dozen times so far for trying to dip my finger in just about every bowl I can reach." 
    "I have been forbidden from touching anything unless specifically asked to do so." 
    show natsuko 8k at t11
    n "[player], I need the food coloring." 
    n "The batter is going in the oven soon." 
    "Natsuko watches my every move as I reach into the bag next to the table and pull out a small box that holds 5 bottles of different colored dye."
    mc "What color are you making the batter?"
    n 9l "Well, each batch will be a different color." 
    n "That way everyone can pick their favorite even if the filling is the same."
    mc "Neat." 
    mc "Are we doing the same with the filling?"
    n 10l "Do you want to?"
    mc "Sure, it sounds like fun." 
    mc "Whatever we can do to make these as creative and eye-catching as possible."
    n 10z "Yeah, now you're getting it, [player]!" 
    n 9j "Now you're putting your heart into it and starting to have fun."
    mc "I sure am!"
    "God, I want to shove my entire head into one of these bowls of batter right now." 
    "It's torture not being able to taste anything." 
    "I watch forlornly as Natsuko separates the batter into smaller bowls and puts a few drops of food coloring into each." 
    "Natsuko catches the intense way I'm gazing at the batter." 
    n 10d "Cool looking, isn't it?" 
    n 9y "Baking isn't about following instructions, you know." 
    n 9l "It's all about presentation." 
    n "Making people's eyes light up at just the sight of your food is just as good as the moan of satisfaction they give after tasting it."
    mc "You're amazing at this." 
    mc "Baking must be your life's calling."
    n 10s "...No..." 
    n "Not at all."
    mc "Really?" 
    mc "That's a pretty lackadaisical response from someone who loves baking."
    show natsuko 8au at t11
    "Natsuko suddenly stops mixing a batch of blue batter, staring into it with a sad expression."
    n "Just because someone is really good at something doesn't mean they really like doing it..."
    mc "..."
    n 13av "Sometimes...a person is only really good at something because..." 
    n "They were forced to do it..."
    show natsuko 13s at t11
    "Natsuko quickly snaps out of his melancholy daze."
    n 13b "Anyway...here."
    "He quickly changes the subject and I'm shocked when he puts down his bowl of blue batter and hands me a large bowl full of cream-filling and a whisk."
    n 10c "I'm still using the mixer, so mix this until there are no more lumps." 
    n "When you're done, we'll add some food coloring to it." 
    n 10b "Keep your fingers out of it." 
    n 10w "I'm serious."
    hide natsuko
    with wipeleft
    "It takes all of my will power to focus on mixing the stuff." 
    "I take the whisk and give it a careless swing around the bowl." 
    "About a half a cup of the mixture flies out of the bowl and splatters on the ground."
    show natsuko 13g at t11 
    "I coyly look up at Natsuko to see him giving me an agitated glare." 
    n 13b "Are you even trying?"
    mc "Trying...to make a mess?" 
    mc "No. That's all happening naturally."
    n 10x "Jeez..." 
    n "I'll be here all night if you do it like that." 
    n 10c "Here."
    "Natsuko grabs the bowl from me." 
    "He takes the whisk in one hand and uses the other to tilt the bowl back."
    n 10r "You really need to...beat...the crap out of it!" 
    n 10a "See?"
    "After only a few seconds, the consistency of the cream filling has already improved, forming firm fluffy peaks." 
    "I watch, puppy-eyed, as Natsuko takes a finger and dips it into the cream, scooping up a dollop and popping it into his mouth."
    n 13z "Ah...perfect consistency!"  
    n 12p "Whoa!" 
    "I launch my finger towards the bowl in an attempt to have a taste of the fluffy mounds only to have Natsuko pull the bowl away and lightly slap my wrist." 
    n 12b "Hey, hey, hey!" 
    n 11b "How many times do I have to tell you to keep your gross fingers out of the bowls?"
    mc "Come on, man!" 
    mc "You're killing me here!" 
    mc "You haven't let me taste anything!" 
    mc "I just want a little sample..."
    "I start to fight back, reaching for the bowl once again."
    n 9x "I'm the chef, and it's my job to make you wait to sample anything until we're done!" 
    n 10f "Now, back off!"
    "Natsuko grabs my hand and pushes back." 
    mc "Well, my job is to get in the way and make a big mess!" 
    mc "And you are seriously impeding my duties so just let me taste the friggin' cream already!"
    "My argument makes absolutely no sense, but at this point, I don't care." 
    "I want that sweet stuff in my mouth." 
    "I push harder, just enough for my finger to reach the lip of the bowl." 
    "I successfully scoop out a dollop just as Natsuko pulls the bowl away with all his might."
    mc "Ah...!"
    "The force of Natsuko pulling me causes me to stumble, making him stumble in turn." 
    "My hand with the cream filling on it brushes against his face, wiping that precious dollop off my finger and across his cheek."
    n 12v "Ugh!" 
    n 12o "You got a big glob of it on my face!"
    mc "Gee, I wonder whose fault that is?" 
    n 9p "Yours, of course!" 
    n 10b "Keep your fingers out of the bowls!"
    mc "Let me taste something!" 
    n 10o "Not until we're done!"
    "Natsuko sets the bowl on the counter behind him and stands in front of it protectively, arms outstretched." 
    "I'm at my wit's end." 
    "I need to get my fix..." 
    "By any means necessary." 
    "I suddenly lunge." 
    show natsuko 12p at t11
    "Natsuko holds up one hand, but I'm faster." 
    show natsuko 11f at t11
    "I grab him by the wrist." 
    "He tries to use his other hand to fight back, but I grab that one too."
    show natsuko 11o at t11
    "I push back with all my might, shoving him beyond the counter and pinning him against the wall..."
    scene n_cg3_base
    with dissolve_cg
    n "Gah!" 
    n "L-let me go!"
    mc "Not a chance!" 
    mc "You won't let me taste anything because you don't want my fingers in the bowls?" 
    mc "Fine, then." 
    mc "You leave me no choice!"
    n "...Ah...!"
    "Before he has a chance to respond, I lean my body into him." 
    "Our faces are practically touching when I suddenly flick out my tongue and slowly drag it across his face, licking off the cream." 
    show n_cg3_exp1 at cgfade
    n "Wh-wh-what--?!" 
    n "D-Did you just..."
    n "Guh...!"
    "Natsuko is so taken aback that he can't even figure out how to get mad at me."
    "He can't even seem to figure out what's going on right now." 
    "He looks away, his face entirely red."
    "But then..."
    show n_cg3_exp2 at cgfade
    "His expression changes."
    "His gaze suddenly becomes amorous. He looks back at me." 
    n "...[player]..." 
    n "You know..." 
    n "Once we put those donuts in the oven..." 
    n "..." 
    show n_cg3_exp3 at cgfade
    n "We'll have, like, a good 12 minutes to do {i]whatever{/i} you want."
    mc "..."
    "Wait...what?"
    "Did he just..."
    "I stare at him in shocked silence."
    "Okay...{i}I'm{/i} not even sure what's going on right now." 
    "I mean, Natsuko has always been pretty forward, but this..."
    "I don't know how to respond to this."
    "My breathing becomes shallow and suddenly, I'm feeling a bit dizzy." 
    stop music fadeout 2.0
    scene bg kitchen
    with dissolve_cg
    play music fire_alarm
    "The screech of the fire alarm kills the tension immediately." 
    "Startled, I reel back while Natsuko rushes to the oven."
    mc "What the--...You haven't put any batches in yet!" 
    mc "What's burning!?"
    show natsuko 12v at t11
    n "*Cough*" 
    n 12p "Jeez, no wonder!"
    hide natsuko
    with dissolve
    "I can feel my face ignite with embarrassment when Natsuko grabs an oven mitt and pulls out a dirty tray, tossing it on top of the stove." 
    stop music
    play music t6
    "The fire alarm stops within moments."
    show natsuko 10b at t11
    n "I told you to check the stove before preheating it, didn't I?"
    mc "Uh...yes." 
    mc "Yes you did."
    n 13b "And did you?"
    mc "I believe the smoldering evidence sitting on top of the stove is proof enough that I did no such thing."
    n 10x "Oh, for Pete's sake..." 
    n 10c "Anyway, I'm putting the first batch in the oven now."
    hide natsuko
    with dissolve
    "And, just like that, we're back to baking." 
    "I have mixed feelings about this."
    "I mean, the baking is fun and all..."
    "But I'm curious what would have happened if that stupid fire alarm didn't go off."
    "It's kind of frustrating." 
    "I watch as Natsuko slides the batch of donuts into the oven." 
    "Meanwhile, I dip my finger in the filling bowl and scoop a massive dollop of cream into my mouth while his back is turned."
    scene bg kitchen
    with wipeleft_scene
    show natsuko 10l at t11
    n "Man, those are smelling real good!"
    "The donuts are ready to be pulled out of the oven." 
    "A blast of sweet-smelling warm air fills the room the moment Natsuko pulls open the oven door." 
    "My mouth waters." 
    n 10j "They look nice, don't they?" 
    n "Wait until we decorate them." 
    n 8l "Empty out that last bag." 
    n "We're gonna need everything in it." 
    n "Hand me the piping bags and metal tips."
    hide natsuko
    with dissolve
    "I get to work pulling everything out of the last bag." 
    "I'm a little overwhelmed by the variety of decorations Natsuko brought." 
    "Several small jars of sprinkles, walnuts, toasted coconut and chopped almonds are among the different options alongside bags of chocolate chips and peanut butter chips." 
    "While the donuts were in the oven, Natsuko and I made different colored icing as well as separated the cream filling to make several colors of that too." 
    "Natsuko returns to the table, having scooped different colors of icing and filling into numerous bags, each tipped with a different metal tube." 
    "He also sets a tray of cooled baked donuts in front of us."
    show natsuko 10z at t11
    n "Now, we do the fun part!" 
    n 9l "You can be as creative as you want with the decorations, but keep in mind this is a literature event, so let's try to come up with a matching theme."
    mc "What about this one with the thin tip..."
    "I pick up a bag of chocolate ganache which is tipped with an ultra thin pipe."
    mc "You can write with this one, right?" 
    mc "Let's write words on the donuts." 
    mc "It'd be fun to see people choose a donut based on a word they like."
    n 9d "Say...that's a good idea!" 
    n 13a "You know..." 
    n 13d "You may be lousy at baking, but I do like the way your mind works!"
    mc "Gee, thanks." 
    mc "I'm sure there's a compliment in there somewhere."
    show natsuko 10ac at t11
    "Natsuko looks at the decorations for a moment, thinking to himself." 
    "No doubt, designing them in his head." 
    "Afterward, he grabs two different colored donuts and places them in front of me." 
    "He grabs two for himself as well."
    n 8a "These didn't come out as nice as the others, so we'll use them to practice on." 
    n 9a "Get a feel for the pipe bags, execute a few ideas." 
    n "When you've got a good groove going, you can start decorating the good ones for real." 
    n 9z "And the best part is, you can eat your two practice donuts when you're done, deal?"  
    n 12p "Ack!!"
    "I look up at Natsuko upon hearing his surprised exclamation." 
    "Crumbs are flaking from my face." 
    "I have already stuffed the donuts he's placed in front of me into my mouth."
    mc "Um...dibv vu fay fomfing?"
    show natsuko 12r at t11
    "Natsuko sighs and shakes his head."
    n 11c "You know what?" 
    n "I'll do the main decorating." 
    n "You write a word on each donut."
    n 10c "Can you at least do that?"
    "I smile and nod excitedly."
    mc "Uh-huh!"
    n 13w "Fine. NO dirty words, though!"
    mc "Aw..."
    "My smile goes away."
    scene bg kitchen
    with wipeleft_scene
    "When we're finished, Natsuko lines the donuts up side by side to admire our work." 
    show natsuko 10l at t11
    n "These turned out so much nicer than I ever imagined they would!" 
    n 10z "Good job, partner!"
    mc "Right back atcha." 
    mc "Those are some pretty donuts, I must say."
    "I, too, admire the amazing variety of donuts we've created." 
    "There are cream-filled donuts and donuts with holes in them." 
    "Some are glazed, some are powdered." 
    "Some are covered with icing and other with sprinkles." 
    "Some are topped with nuts while others are topped with chocolate chips." 
    "Some are striped and some are plain." 
    "The colors pop where they should but don't outshine the ones with simpler decorations." 
    "What a lovely display." 
    "I just want to roll around in them."
    mc "I wish I could have one right now."
    n 9c "You can have ONE." 
    n "And only one."
    "I waste no time in reaching for the one I'm eying." 
    "It's a chocolate covered one with rainbow sprinkles and cream filling." 
    "But rather than inhale it, I nibble it daintily, enjoying the fresh flavor." 
    "They taste as delicious as they look."
    mc "These are amazing, Natsu." 
    mc "You've got to try one."
    "I offer him a bite of my donut."
    show natsuko 12k at t11 
    "He opens his mouth automatically like he's going to bite down, then suddenly stops and looks away."
    n 12q "Thanks, but...I already know what they taste like." 
    n 10s "Besides, I'll be eating dinner soon and I don't wanna spoil my appetite."
    mc "I'm the opposite." 
    mc "I'd down 10 of these and still eat dinner."
    n 13c "Well, as healthy as that sounds, not all of us can wolf down 14 kilos in one sitting."
    n 10k "Anyway, I was hoping we'd have time to hang out, but I better get home."
    mc "Already?"
    mc "Couldn't you stay a little longer so we could play a video game?"
    n 9n "I...mmm..."
    "Natsuko pauses, looking away."
    n 10u "I really would love to..."
    n 10q "But the thing is...my mom won't be home until late tonight..."
    n "I'll get to have the house to myself."
    n 10s "It...it doesn't happen too often..."
    n 10n "So I have to take advantage of it when I can."
    mc "How come?"
    n 10au "..."
    n 10av "Let's just say..."
    n "I kinda have to be a different person when she's home."
    n 10q "When I'm home alone..."
    n "I get to...be me..."
    "I narrow my eyes suspiciously."
    "I wonder what he means by that?"
    "I'd ask if I could go to his his house since his mom won't be home..."
    "But I'm not sure I want to risk getting him in trouble if she comes home early."
    n 12b "This is all your fault, you know!"
    "His mood suddenly shifts."
    n 13b "If I didn't have to constantly babysit you all afternoon, we'd have been done sooner and had more time to hang out!"
    "Well, he quickly turned back into his normal bratty self."
    mc "Oh, sure." 
    mc "Blame me."
    n 11c "It was 100\% your fault."
    "He's not lying."
    "We'd have been done hours ago if it weren't for me screwing around the entire time." 
    "But at least we had fun."
    mc "Should I bring the donuts tomorrow?"
    show natsuko 10ap at t11
    "Natsuko laughs loudly."
    n "You must be joking!" 
    n 10y "I'm not leaving them with you!" 
    n 9d "They're coming with me tonight." 
    n 10c "I don't trust you, or Satori for that matter, to be with those donuts all night." 
    n 9w "That's why I brought this Tupperware."
    "Natsuko begins carefully lining the donuts up in the special trays in the Tupperware." 
    "Ah, well." 
    "It was worth a shot."
    mc "You are wise not to trust Satori and I." 
    mc "We would have destroyed those donuts."
    n 13y "Trust me, I know!"
    hide natsuko
    with dissolve
    "The mention of Satori takes me back to our conversation this morning." 
    "I remember how helpless I felt." 
    "There's never been a time we haven't shared everything with each other." 
    "I wish he'd tell me what I can do to help..."
    show natsuko 8l at t11
    n "Okay, I have all my stuff packed." 
    n 10z "Good work today!"
    mc "Thanks!" 
    mc "I had a lot of fun!"
    scene bg residential_day
    with wipeleft_scene
    "Just like that, Natsuko is already about to leave." 
    "It feels like the afternoon went by in a flash." 
    "More than that, did I get the opportunity to get closer to him like I wanted?" 
    show natsuko 8d at t11
    n "Well, I guess I'm off, then." 
    n "Thanks for all the..." 
    n 10t "Um...help today."
    mc "Let's not kid ourselves." 
    mc "I was no help at all."
    n 10z "Haha!" 
    n "Well, thanks for the entertainment, then, I guess." 
    n 10as "I'll see you tomorrow."
    mc "Natsu, wait!"
    show natsuko 10k at t11
    "I speak without thinking."
    "I've been doing an awful lot of that lately."
    n "Eh?"
    mc "About today..." 
    mc "I'm serious when I said I had a lot of fun." 
    mc "Not just the baking..." 
    mc "But hanging with you in general." 
    mc "This doesn't need to be a one-time thing, is what I'm saying." 
    mc "I want to spend time with you again, if at all possible." 
    mc "Whether you want to read comics, or play video games..." 
    mc "Whatever." 
    mc "I'm up for it."
    "Natsuko gives me an intense look."
    n 10ar "Do you...mean that?"
    mc "Yeah, I do." 
    mc "I want to do this again."
    n 10m "[player]..." 
    n 10u "I-I didn't think..." 
    n "I mean, of everyone in the club..."
    "Natsuko sets the bags and Tupperware on the ground and turns to face me fully."
    n 12m "I'm sorry I had to leave so early!" 
    n "I really didn't want to." 
    n "I would stay here all day if I could." 
    n "I feel the same way as you..."
    show natsuko 12e at nface
    "Natsuko steps closer." 
    "I may call him \"Shorty\" but in reality, we're almost the same height." 
    "At this point, his face has gotten very close to mine." 
    "Standing inches from me, he looks into my eyes." 
    "I feel his hands suddenly curl around mine." 
    "His rose-colored cheeks and matching eyes fill my vision, along with his slightly parted lips." 
    "What...is happening...?" 
    "He leans closer." 
    "I can feel his breath against my lips."
    n "I've felt this..." 
    n "For a while now..."
    n 12o "...!"
    show natsuko at t11
    "Natsuko suddenly jumps back."
    n 12p "S-Satori!"
    show natsuko at t21
    show satori 11i at t22
    mc "...!"
    s 11j "Hey, [player]." 
    s 11at "Hey, Nat." 
    s 11i "What are you guys up to?"
    mc "Uh...nothing." 
    mc "We finished working for today and Natsu was just leaving."
    show natsuko 12r at t21
    s 11au "He is?" 
    s 11at "Bummer. Sorry I didn't come sooner." 
    s "We could've all hung out."
    n 10q "It's, uh..." 
    n 10i "It's nice to see you, Satori." 
    n 10h "I wish I could stay, but I have to get home."
    s 11ac "Oh."
    s 11at "That's a shame." 
    s 17j "Well, I'd hate to keep you." 
    s 11at "So I guess we'll see you at the festival, yeah?"
    "I can't help but notice Satori is acting passive-aggressively forceful." 
    "Is he trying to drive Natsuko away?" 
    show natsuko 10u at t21
    "Natsuko seems to pick up on it too." 
    "He looks at me briefly."
    n 10n "Yeah, well..." 
    n "I guess I'll see you tomorrow, then--..."
    s 11ac "Goodbye, Nat."
    show natsuko 10m at t21
    "Satori cuts him short, staring Natsuko in the eye in an uncomfortably domineering way." 
    show natsuko at thide
    hide natsuko
    "Natsuko nods obediently, gathers his bags and the Tupperware of donuts, then hurries off with his head down." 
    "What..." 
    "The hell..." 
    "Was that about?" 
    show satori 11g at t11
    "Satori suddenly turns to me and his expression instantly softens."
    mc "Satori...I, uh..."
    mc "I thought you didn't want to come over toda--..."
    s 17h "Look...can we talk?"
    "Satori suddenly interrupts me."
    mc "Talk?"
    s 15j "Yes, talk. We need to talk now."
    "There's urgency in his tone." 
    "In fact, his entire demeanor is tense and his expression seems worried." 
    "Even his temper is short." 
    mc "Of course we can."
    s 11f "Good." 
    s "Let's go to your room." 
    s "And hurry." 
    s 12k "Before I lose my nerve." 
    show satori at thide
    hide satori
    "Satori hurries past me." 
    "I struggle to keep up as we slip back into the house and head upstairs."
    $ persistent.clear[4] = True
    $ renpy.save_persistent()
    return

label ch4_exclusive_yuri:
    stop music fadeout 2.0
    scene bg residential_day
    with wipeleft_scene
    play audio t6
    "I exit Satori's house." 
    "On the way home, I still find myself feeling uneasy." 
    "I try to focus my thoughts on Yuuri, convincing myself that tomorrow will be a better day for everyone, including Satori." 
    "I approach my house to see Yuuri waiting at the door." 
    "He must've just knocked." 
    "I quietly walk up behind him."
    show yuuri 8v at t11
    y "Hmm...she must not be home..."
    mc "Try texting her."
    show yuuri 12n at t11
    "Yuuri jumps a little and turns to face me." 
    y "Ah--!" 
    y 12s "...Thank goodness." 
    y 11b "I got a little worried when you didn't answer your door."
    mc "You're a bit early." 
    mc "Sorry I wasn't home yet."
    y 8d "It's fine." 
    y 8b "Don't worry. I wasn't waiting long." 
    y 9b "I just got here in fact."
    mc "I know. I saw you coming from across the street." 
    mc "Anyway, let's head inside." 
    mc "I see you brought a bunch of stuff with you."
    y 8c "That's right." 
    y 11a "And did you get all the things I asked you to buy as well?"
    mc "I'm pretty sure I got everything." 
    mc "Sorry if I missed anything, though."
    y 8d "I'm sure we'll be fine."
    scene bg Fmbedroom
    with wipeleft_scene
    show yuuri 8i at t11
    "I take Yuuri to my room." 
    "While he's busy looking around, I take the time to check him out."
    "It's the first time I've seen him outside of school, after all."
    "I'm digging his posh sweater."
    "..."
    "Them tight pants, though..."
    "..."
    "..."
    y 11b "Your room is very tidy."
    mc "...!"
    mc "Huh?"
    mc "Oh! Right..."
    mc "Thanks. I cleaned it before you came over."
    y 10c "That was very considerate of you."
    mc "Well, I'd be very embarrassed if you came over while it's messy." 
    mc "Ah, wait! Yuuri, don't touch that!"
    "Yuuri pulls one of my games from my shelf." 
    "He bumps the game next to it and it causes a domino effect."
    show yuuri 12n at t11
    "Yuuri instantly retracts, realizing what he's done."
    "All the games fall into each other until, finally, they topple against the controller of my favorite console, sending it flying off the edge of the shelf." 
    "That controller is held together with tape and glue from all the times I've flung it across the room in frustration."
    "It can't survive another drop to the ground."
    "I launch myself at it with an eager, open palm."
    "I land at the base of my TV stand."
    "Miraculously, I catch the controller just before it hits the ground."
    show yuuri 10w at t11
    "I hear Yuuri give an audible sigh."
    "I smile triumphantly."
    mc "Ha! Like a ninja!"
    play sound bap_half
    $ pause (0.5)
    play sound bap_half
    $ pause (0.5)
    play sound bap_full
    mc "Ack!"
    show yuuri 12e at t11
    "Three of the games slip off the shelf and hit me, one at a time, right in the face."
    y 12p "[player]!"
    "Yuuri comes rushing over and quickly helps me to my feet."
    y 12t "Are you alright?!"
    y 12v "I'm so sorry...I wasn't thinking!"
    y 11t "I was just spacing out, I suppose..."
    mc "I'm fine, I'm fine..."
    "I mumble that as I gently rub my forehead."
    y 12t "Are you sure? You have a red mark right there..."
    mc "I'm okay! Really!"
    mc "My head can take a lot of punishment."
    y 8v "If...if you insist."
    "He clasps his hands firmly behind his back, as if to keep track of them." 
    mc "So...shall we get started?"
    y 8y "Yes, let's." 
    y "I have a few things that I could use your help with today." 
    y "Decorations and other atmospheric enhancements." 
    mc "Atmospheric Enhancements?"
    y 8c "That's right. Like mood lighting and aromatherapy candles."
    mc "Ooh...That sounds really nice and relaxing."
    y 8a "Thank you." 
    y 9k "We wish to take our guests to a faraway place." 
    y 8f "Even though many will just be dropping in out of curiosity." 
    y 8ac "And donuts, I suppose..." 
    y 9f "Either way, I'm determined to provide them with an experience that will leave them wanting more."
    mc "That sounds amazing!" 
    mc "Man, it's easy to forget what an intense person you are!"
    y 8t "Intense?" 
    y 8v "Is that a bad thing or a good thing?"
    mc "It's actually what I like best about you."
    y 8t "You do?" 
    y 8u "That makes me feel relieved." 
    y 8s "And... Rather happy."
    mc "That's good!" 
    mc "I don't want you to feel anxious around me. Just relax."
    y 8b "Speaking of which..." 
    y 10b "I actually brought some things for relaxation."
    "Yuuri reaches into one of the bags he brought." 
    "Things for relaxation?"  
    "Is he talking about drugs?"
    y 11b "I was going to use them during the poetry event..."
    "After rummaging in the bag for a few moments, Yuuri returns with a bunch of candles and a cylinder shaped object." 
    "What's that for?" 
    "Is it for the drugs?"
    y 10b "I visited a shop on the way here and grabbed these." 
    y 11j "I planned on covering the windows with black paper and using candles to light the room." 
    y 10b "I think that would be amazing, don't you?"
    mc "Yeah. Really cool."
    "That'll totally enhance our weird drug trip..." 
    mc "So..." 
    mc "The wooden thingy..." 
    mc "That's for...?"
    y 11j "Ah, this? This is for diffusing essential oils."
    y 11b "How familiar are you with aromatherapy?" 
    y "It's one of my favorite contributors for a positive atmosphere." 
    y "Depending on the oil or herb you use, it can change the mood of the air itself." 
    y "You can feel it permeate your body." 
    y 11m "Relaxation, positive energy, romance, reflection..." 
    y "It's almost like magic."
    "Yuuri takes the cylinder and pushes a button on the bottom." 
    "In just a moment, a thin ray of vapor begins to spout through a small hole on the top." 
    "Ah! There's those tasty, tasty drugs."
    mc "That smells really pretty." 
    mc "What mood is that one for?"
    y 10a "It's a Jasmine essential oil." 
    y "It smells kinda sweet and flowery, right?"
    mc "Yeah, it's amazing"
    "Whatever gets rid of that foot or cheese smell that seems to linger in here."
    y 11b "I chose Jasmine for the event because it provides more than relaxation." 
    y "Jasmine enhances your emotions and helps you feel them flow through your body." 
    y "You feel warmer and your heart pounds more heavily." 
    y 8d "Don't you think that will be perfect for sharing our poems?"
    mc "It sounds very suitable."
    "Because nothing goes better with poetry reading than tripping balls." 
    "Actually, that might be true..."
    mc "You seem to have a lot of knowledge about this, so I'll trust your opinion!" 
    show yuuri 8c at t11
    "Yuuri smiles, clearly enjoying himself." 
    "I watch, a little concerned, as he sets up numerous candles around the room." 
    "He lights them with what appears to be a very fancy lighter." 
    "By the time he's done, there are about 14 lit candles all around my room, which suddenly feels more flammable than usual." 
    "Satisfied, Yuuri grabs a large spool of thin ribbon from his bag and sits on the ground." 
    "I sit next to him, nervously eying the candles."
    mc "What's the ribbon for?"
    y 8j "Well..." 
    y 9b "Did you purchase the origami paper I asked you to get?"
    mc "Yep, got it right over here..."
    y 8d "Excellent. We won't be using it to fold origami." 
    mc "Alright..."
    "There goes six hours of my life trying to learn how to make a friggin' swan."
    y 9a "Instead, what I'd like to do is write a different word on each paper." 
    y "We'll need about a hundred of them." 
    y "Then we're going to attach them to pieces of ribbon and hang them in the doorway of the classroom, creating a curtain of words." 
    y 8c "Wouldn't that be interesting?" 
    y "It would also catch the eyes of those passing by." 
    y 8b "It may tempt some to peek inside."
    mc "That's insanely creative, Yuuri!" 
    mc "I had no idea you were so good at this."
    y 8u "Well, I suppose I do get a little..." 
    y 8c "Intense, as you put it."
    "Yuuri gives me a big smile." 
    "I can definitely tell he's starting to relax." 
    "I hope he's starting to really become comfortable with me and that this behavior isn't a direct result of his little vape machine." 
    "Or perhaps it's the excitement he feels from sharing something he enjoys?"
    y 8a "Here's a marker, [player]." 
    y "You can write any characters you want."
    y "I'll help you once I finish cutting the ribbons."
    mc "Alright."
    hide yuuri
    with wipeleft
    "Sitting on the floor together, the two of us get to work." 
    "I carefully draw a different character on each paper, doing my best to manage my bad handwriting, and to avoid all the words I really want to write." 
    "Yuuri unravels a long strand of red ribbon to his desired length." 
    "Then, he reaches into his pocket and pulls the lighter back out." 
    mc "Whoa..."
    "The lighter is strangely beautiful up close." 
    "There are intricate patterns etched into it and the lighter itself is a shiny dark blue." 
    "He flicks it and a sharp green flame bursts from the top." 
    "Holding the ribbon taut, he waves the flame far beneath the ribbon." 
    "Like magic, the ribbon breaks without the flame even touching it." 
    mc "That's no run-of-the-mill gas station lighter, is it?" 
    mc "It looks very fancy."
    show yuuri 8v at t11
    y "Oh...um..."
    "Embarrassed, Yuuri looks away."
    mc "What's wrong? Is it something I said?"
    y 12o "You're... gonna think I'm weird."
    mc "Yuuri..." 
    mc "I already think you're weird." 
    mc "There's nothing wrong with that, you know?" 
    mc "Normal is boring." 
    mc "In case you haven't noticed, I'm a little strange myself."
    y 12q "Ah...well, as long as you promise not to freak out..."
    mc "I promise."
    y 10t "Alright. Well, the thing is..." 
    y 10u "I'm kind of into fire." 
    y 11u "It's just...so beautiful." 
    y 11t "I can't help it. I don't know what it is." 
    y 11s "The combination of raw beauty, untamed power and danger..." 
    y 10v "Ah! What am I saying?" 
    y 12t "Please don't think I'm sick or anything..."
    mc "Ahahahaha..."
    y 12o "You're laughing at me..."
    mc "No, no. That's not it..."
    "And it's definitely not nervous laughter brought on by the realization that I'm sitting in a room surrounded by flames with a potential pyromaniac..."
    mc "It's just funny how nervous you got about sharing." 
    mc "I just...I think you're kinda cute when you get all embarrassed like that."
    show yuuri 12e at t11 
    mc "It's an interesting thing to be into, I guess." 
    mc "But you know what? It suits you."
    y 12u "Suits me?"
    mc "Yeah...It's kinda intense, you know?" 
    mc "Besides, it's a really cool looking lighter that makes pretty green fire."
    y 10u "Yes...it is..."
    show yuuri 10g at t11
    "Yuuri's expression suddenly intensifies."
    y 10g "Would..." 
    y 10t "Would you like to...hold it?"
    mc "Sure, I'll check it out." 
    hide yuuri
    with dissolve
    "Yuuri carefully hands me the lighter." 
    "I take it and turn it around in my hands." 
    "It feels heavy and solid for a lighter." 
    "Where'd he even get this?" 
    "Curious of the flame, I ignite it." 
    "I stare, mesmerized at the hard green flame that hisses out like a tiny blow torch." 
    "Not wanting to waste the fluid, I let the flame die." 
    "I go to hand it back to Yuuri." 
    "Without thinking, I wrap my fingers around the top of the lighter."
    mc "--OW!" 
    show yuuri 10p at t11
    y "[player]!" 
    y "Why did you do that!?"
    mc "Because I'm dumb and I don't think about things before I do them!"
    y 12n "I'm sorry, I should have warned you." 
    y 12o "The top of the lighter gets really hot when you let the flame linger." 
    y 12p "Oh, no!"
    "I flick my hand wildly, trying to fan some cool air on the burn I've incurred on the tip of my finger." 
    "I look at it." 
    "The skin is red and shiny."
    "A slight bubble has already formed." 
    "Suddenly, Yuuri grabs my hand and holds it to his face to give the burn a closer look."
    y 10af "Ah..."
    "Yuuri moans slightly and visibly fidgets." 
    mc "If it's making you squeamish, I can go put a band-aid on it..."
    show yuuri 10l at t11
    mc "--A-Ah!!"
    "Without warning, Yuuri flicks out his tongue and licks the wound." 
    "Then, he gently blows on it in an attempt to cool off the burn."
    "Then he licks it again."
    "He repeats the process."
    "His tongue gently curls around my finger this time."
    "It feels kinda..."
    "...!" 
    "Okay, this is getting weird!" 
    mc "Ah...Yuuri..."
    show yuuri 10n at t11
    "As if he just realized what he was doing, Yuuri suddenly releases my wrist and reels back."
    y 12n "Oh my...!" 
    y "Please forgive me!" 
    y 12o "I-I wasn't thinking..."
    "Yuuri lowers his head, his face burning up."
    y 12v "That...was the most embarrassing thing I've done in my life!" 
    y "How could I do something like that?" 
    y 12ag "I'm sorry. I'm so sorry..."
    "Granted, it was a little alarming and I wasn't expecting it..." 
    "But it's obvious he was just trying to help." 
    "Besides, I've done way more embarrassing things than that..."
    mc "Yuuri ...it's fine." 
    mc "Don't worry about it."
    y 10ah "Mmm..."
    "Yuuri doesn't lift his head." 
    "Oh man, I don't want him to be like this for the rest of the afternoon!"
    "..." 
    "I suddenly get a terrible idea."
    mc "Alright, you know what?..."
    "I lunge forward and, grabbing Yuuri by the sweater, pull him down until his face is level with mine."
    show yuuri 10e at t11
    "Then I lean in and lick his cheek." 
    "I release him from my grasp and pull back."
    show yuuri 12af
    mc "Boom! Now we're even!"
    "Yuuri is frozen with shock. He looks at me like I did something wrong."
    y 12ai "..."
    mc "Do you see what I did there?"
    y  12af "..."
    mc "..."
    "I guess it wasn't as self-explanatory as I thought..."
    mc "Well...I didn't want you to feel bad about the weird thing you just did, so I did something even weirder cuz I thought it would...fix...everything..."
    "Huh...now that I say it out loud, it still makes no friggin' sense..."
    "Why did I do this again?"
    "I catch the glimmer of the spit-trail I left on Yuuri's cheek." 
    "I smile coyly." 
    mc "That was a lot more saliva than I intended."
    mc "I, um...." 
    mc "I can get you a tissue..."
    show yuuri 12u at t11
    "Yuuri's expression suddenly breaks." 
    show yuuri 12c at t11
    "A large smile creeps across his lips." 
    "He starts chuckling quietly at first." 
    show yuuri 12aj at t11
    "But it quickly escalates to the same hearty, genuine laugh I heard the day Mateo made us recite poems to each other." 
    "It reverberates through the room." 
    "The intensity and sincerity of the laugh makes me laugh too." 
    show yuuri 10ak at t11
    "We wind down after a few moments." 
    "Not gonna lie...I think the Jasmine gave us a little buzz." 
    mc "I like your laugh."
    y 11al "I like that you make me laugh." 
    y 10u "I...I don't do much of it." 
    y 8s "So it's nice to be around someone who makes me feel so happy."
    mc "I'm glad to hear that."
    "I smile a little." 
    "Well, my ideas may be terrible but at least they get the job done." 
    "Once again, the tension is quickly lifted."
    y 11f "Where do you keep your bandages?"
    mc "Oh. Don't worry about it." 
    mc "It was just a small burn." 
    mc "It's already feeling better."
    hide yuuri
    with dissolve
    "We each resume our respective activities." 
    "I watch as Yuuri's flame slices through air like a laser, cutting through the ribbon with ease." 
    "Meanwhile, I continue to make progress on the paper."
    scene bg Fmbedroom
    with wipeleft_scene
    "After we finish attaching the paper to the ribbons, we lay them all out side by side." 
    "It looks better than I expected and will make a very effective door curtain." 
    mc "It looks great!" 
    mc "Excellent job coming up with this, Yuuri!"
    show yuuri 8d at t11
    y "Ahaha...thank you." 
    y 9b "Let's move on to the next task."
    mc "Sure, what's next?"
    y 9a "We're going to create a banner." 
    y "That's why I asked you to buy the paint tablets." 
    y 9f "We'll need about six cups of water to put each of the tablets in." 
    y 8s "Would you please prepare that for us?"
    mc "Of course."
    y 9f "Not too much water, now." 
    y "If you fill the cups too much, the paint will be too diluted."
    mc "Got it."
    hide yuuri
    with dissolve
    "Taking Yuuri's advice, I decide to use small plastic bathroom cups rather than full sized glasses." 
    "I put them on a plate to catch any paint that drips, then bring it back into my room."
    mc "Yuuri?"
    show yuuri 8t at t11
    y "Yes?" 
    "I come in to see Yuuri unrolling the sleeve of his sweater and pulling it back over his arm." 
    "He seems out of breath." 
    "I'm prepared to question this action but I become distracted..."
    "Why does it smell like bacon in here all of a sudden?"
    mc "Ah, nothing..."
    mc "Is it hot in here?" 
    mc "Your face is kinda red."
    y 8q "No, no...not at all." 
    y "Everything's fine." 
    y 9j "Let's mix the paint, shall we?"
    hide yuuri
    with dissolve
    "Yuuri hurriedly dismisses me and takes it upon himself to unwrap the tablets, dropping them into the cups."
    show yuuri 11f at t11
    y "So... I thought we would do something simple that would look very nice." 
    y "I'd like to paint a gradient across the banner." 
    y "Starting with colors for a sunrise, then daytime, then sunset, then nighttime." 
    y 11b "Once it dries, I'll write an inspirational quote across the banner." 
    y "We can hang it on the wall behind the podium at the front of the classroom." 
    mc "Cool. Whatcha gonna write?"
    y 8u "Well... I think it would be more fun to surprise you."
    show yuuri 8c at t11
    "Yuuri smiles at me." 
    "Swoon!"
    mc "I do like surprises..."
    hide yuuri
    with dissolve
    "After rolling out the banner, Yuuri and I kneel on opposite sides so we don't get in the way of each other." 
    "Yuuri uses a brush and adds a few dots of different colors across the banner to serve as a color guide when we paint." 
    "Painting on a banner with watercolors feels a lot like the art projects we had in elementary school." 
    "It's both nostalgic and relaxing." 
    mc "This is actually kinda fun." 
    show yuuri 10d at t11
    y "Yes. It is fun." 
    y 10b "I'm glad you think that too."
    "Yuuri stops painting for a moment and thinks to himself."
    y 8m "For me, I don't need to go out and do crazy things to have fun." 
    y 10l "I don't even like to." 
    y 8u "I just want to spend time with one person, doing something simple like reading." 
    y "It doesn't even matter if we don't talk much." 
    y 8a "Just spending time with someone I can trust is all it takes for me to be happy."
    mc "That makes two of us." 
    mc "I like just hanging out with one person, playing a fun video game." 
    mc "We should play together some time."
    "Yuuri smiles gently." 
    y 8s "I knew you'd understand, though I'm not really a gamer..." 
    y 9u "But I wouldn't mind doing that." 
    y 8u "Playing a video game, that is..." 
    y 8s "With you..."
    mc "I'd like that."
    "Yuuri leans over the banner to grab an unused paintbrush." 
    "But I go for it at the same time, causing my head to bump into his."
    mc "Kya!"
    show yuuri 10n at t11 
    "His head smacks me in the exact spot I got pelted with the game cases."
    y 12p "I'm sorry!"
    "I reel back and Yuuri quickly lifts his hands in surprise." 
    y 12t "Are you hurt?"
    "The room suddenly feels like it's lopsided."
    mc "No, no... I'm fine." 
    y 11t "Are you sure?"
    "Probably not as much as I'm trying to put off..."
    "Though seeing two of him right now is pretty cool..."
    mc "Yep!" 
    mc "Nothing goes better with a 1st degree burn than a little head trauma, right?"
    y 10ag "I'm terribly sorry!" 
    y 10t "I should have asked you to hand it to me." 
    y 12n "Ah...your face..."
    mc "Hm? What about it?" 
    "I sit up and look in the mirror over my dresser." 
    "I have droplets of paint on my face and neck."
    "And that red mark on my forehead is bigger now."
    "That's attractive."
    y 10v "I accidentally got paint on you." 
    y 10f "I'm sorry. Hold on, let me go get a towel."
    show yuuri at thide
    hide yuuri
    "He rushes out of the room before I can say anything." 
    "He returns a short moment later with what appears to be a damp towel." 
    "He must have grabbed it from the bathroom across the hall." 
    "He kneels in front of me and hands me one end of the towel."
    show yuuri 11f at t11
    y "I soaked this part in cold water. It's for you to hold against your head."
    "I hold the towel to my bump."
    "I feel instant relief."
    y "This end was soaked in hot water...for the paint."
    "Yuuri hesitates."
    y 10u "Would you like me to...clean it off for you?"
    mc "Hehe..."
    mc "With the towel or your tongue?"
    y 10e "...!"
    mc "...!"
    show yuuri 12am at t11
    "Yuuri gasps a little and swiftly looks away, his face blazing."
    "...Why did I say that??"
    "Especially knowing how easily he gets embarrassed!"
    "I'm almost positive that was my mild concussion talking."
    "I've definitely crossed the line this time."
    mc "Yuuri! I...um...I didn't mean..."
    show yuuri 8an at t11
    "Before I have a chance to apologize, Yuuri looks back at me with a playful smirk."
    y "Forgive me..."
    y 8z "I was just silently regretting not getting the edible paints instead..."
    "His gaze becomes amorous."
    "YES!"
    "I did it! I finally got him to banter with me!"
    "That's so..."
    "..."
    "Wait...does that mean the paint he splattered on me is toxic?"
    "I don't have much time to question it as he begins gently dabbing my face with his end of the towel."
    scene y_cg3_base
    with dissolve_cg
    mc "Ah!"
    y "Is everything alright?"
    mc "Yeah..." 
    mc "It's just..." 
    mc "I forgot it was hot."
    y "Well, you do have a decent-sized bump there."
    y "I expect you to be a little...loopy."
    "I giggle to myself as he continues to clean away the paint drops."
    "The combination of the warmth on my face and the cold on my bump feels like heaven." 
    "Yuuri slowly moves the towel to my neck and begins cleaning off the paint there as well." 
    "Ooh..." 
    "That feels even better." 
    "I can't help but moan a little and close my eyes."
    mc "That..." 
    mc "Feels so good..."
    "I open my eyes slightly." 
    "Yuuri is staring directly into my eyes now." 
    "I'm sure this is the first time he's maintained eye contact with me this long." 
    "He wears the same intense expression I see when he reads his books." 
    "Almost as if he's lost in a daze, enveloped by his own thoughts." 
    show y_cg3_exp1 at cgfade
    "He breathes gently through slightly parted lips." 
    "Suddenly, his face seems to be much closer to mine than it was a moment ago." 
    "I can feel the towel slowly travel past my collar bone..."
    y "Ah..."
    "As if realizing where his hand was going, Yuuri stops and pulls away."
    scene bg Fmbedroom
    with dissolve_cg
    show yuuri 8v at t11
    "We both drop our ends of the towel at the same time."
    y "I'm sorry." 
    y "I...I didn't mean to space out."
    mc "It's...it's okay..." 
    y 8t "H-how's your bump?"
    mc "It's...feeling a little better."
    y 8u "Ah...I'm...I'm glad." 
    hide yuuri
    with dissolve
    "The moment is over as soon as it began." 
    "Yuuri picks up his brush again." 
    "But I can see that's he's clumsier, like he's unable to focus." 
    "I remain silent, forced to ignore the event that just transpired." 
    "I hesitantly retrieve my own brush."
    "Much like Yuuri, my focus has been compromised as well and I fumble with my brush." 
    "We awkwardly continue with our work."
    scene bg Fmbedroom
    with wipeleft_scene
    "Once we finish painting, we take a little break to head downstairs and have some tea."
    "We chat for about 15 minutes before heading back upstairs to finish up." 
    "The banner has turned out very pretty and natural-looking."
    show yuuri 8d at t11
    y "It came out better than I expected." 
    y "I'm really happy with the results."
    mc "Me too." 
    mc "When are you gonna add the lettering?"
    y 8b "When the paint is fully dry." 
    y 9f "It could take a while longer, but it should be dry enough for me to bring it home at least." 
    y "I'll probably do the lettering in the clubroom before the event starts." 
    y "What do you think?"
    mc "Sounds good to me."
    y 8c "Wonderful." 
    y 8b "In that case, I don't think there's anything else for us to do here."
    hide yuuri
    with dissolve
    "Yuuri begins going around the room blowing out candles." 
    "I'm relieved to see the flames finally doused."
    mc "Phew!"
    show yuuri 8c at t11
    y "Ahahaha..." 
    y "Sounds like you're happy this is finally over." 
    y 8a "Was I wrong to assume you were enjoying yourself at least a little bit?"
    mc "Ah! No, that's not what I meant at all!" 
    mc "I was just relieved my room didn't catch on fire." 
    mc "I had a lot of fun with you today."
    show yuuri 8c at t11
    "Yuuri laughs again." 
    y "You're silly, [player]." 
    y 8s "But I'm glad you feel that way." 
    y "I had fun as well." 
    y 9b "And we were very productive and got everything done."
    mc "We sure did." 
    mc "I was a little concerned about time." 
    mc "I need to make dinner soon."
    "I've been starving ever since I smelled bacon earlier."
    y 10i "Ah." 
    y "I was hoping we'd have extra time after finishing the work..."
    mc "Oh?" 
    mc "I mean, if you want to hang out, I could always make a late dinner."
    y 10h "Well..."
    "Yuuri thinks to himself for a moment."
    "My hopes are dashed when my stomach suddenly makes a loud rumbling noise."
    show yuuri 10u at t11
    "Yuuri smiles sadly and shakes his head." 
    y "I think it would be irresponsible to postpone your dinner." 
    y 9s "You should eat at a reasonable hour so you can get to bed at a reasonable hour." 
    y 9ao "We can't have you showing up late tomorrow, after all."
    "Yuuri smiles and winks at me." 
    hide yuuri
    with dissolve
    "As much as I hate to admit it, he's right." 
    "Tomorrow is too important to show up late." 
    "It sucks, because I wish we had more time too."
    mc "Well, I guess you're right..."
    "Feeling downcast, I help Yuuri gather his things." 
    "He looks a little disappointed too, and I can understand why." 
    "It sounds like he rarely gets the opportunity to spend time with friends in a relaxed environment." 
    "But that doesn't mean this is the last time it can happen."
    scene bg residential_day
    with wipeleft_scene
    "Once Yuuri is packed up, I walk him out the door." 
    show yuuri 11b at t11
    y "Thank you so much for having me today."
    mc "No problem." 
    mc "I had a lot of fun and I'm glad I was able to help." 
    mc "Just let me know if you need me to bring anything tomorrow."
    y 10c "I will." 
    y 8u "Anyway..."
    "Yuuri fidgets." 
    y 10v "I guess I'll see you tomorrow..."
    mc "Yuuri, wait!"
    show yuuri 10e at t11
    "I speak without thinking."
    "I've been doing a lot of that lately."
    mc "A-about today..." 
    mc "It's fine we didn't have as much time as we wanted." 
    mc "It just means we can do this again!" 
    mc "Whenever you want, you can come over and we'll read and play some video games..." 
    mc "I mean, since you don't like going out..."
    show yuuri 8s at t11
    "Yuuri smiles as I stumble over my words."
    y 8ap "You're so thoughtful, [player]."
    show yuuri 8aq at yface
    "Yuuri suddenly steps closer." 
    "He places his finger under my chin and lifts my head, forcing my gaze to meet his."
    y "I really like that about you."
    mc "I...ah..."
    show yuuri 8ap at yface
    "I feel my face burning." 
    "How do I respond to that?" 
    show yuuri 12p at t11
    "I don't have much time to think it over as Yuuri suddenly jumps back."
    y "S-Satori!"
    mc "Eh?"
    show yuuri at t21
    show satori 11i at t22
    s 11j "Hey, [player]." 
    s 11at "Hey, Yuuri." 
    s 11i "What are you guys up to?"
    mc "Uh...nothing." 
    mc "We finished working for today and Yuuri was just leaving."
    s 11au "Is he?" 
    s 11at "Bummer. Sorry I didn't come sooner." 
    s "We could've all hung out."
    y 12o "It's, um..." 
    y 12q "It's nice to see you, Satori." 
    y 11q "I wish I could stay, but I'm already late."
    s 11at "Really? That's a shame." 
    s 17j "Well, I'd hate to keep you." 
    s 11at "So I guess we'll see you at the festival, yeah?"
    "I can't help but notice Satori is acting passive-aggressively forceful." 
    "Is he trying to drive Yuuri away?"
    show yuuri 10o at t21 
    "Yuuri seems to pick up on it too. He looks at me briefly."
    y 10j "Yes, well..." 
    y 10s "I'll see you tomorrow then--..."
    s 11ac "Goodbye, Yuuri."
    show yuuri 10v at t21
    "Satori cuts him short, staring Yuuri in the eye in an uncomfortably domineering way." 
    show yuuri at thide
    hide yuuri
    "Yuuri nods then hurries off with his head down." 
    "What..." 
    "The hell..." 
    "Was that about?" 
    show satori 11g at t11
    "Satori suddenly turns to me and his expression instantly softens." 
    s "Hey."
    mc "Um...hey..."
    s 11o "What happened to your head?"
    mc "Huh? Oh...um...ninja fail."
    "He rolls his eyes."
    s 11at "Of course."
    mc "..."
    mc "Satori...I, uh..." 
    mc "I thought you didn't want to come over toda--..."
    s 17h "Look...can we talk?"
    "Satori suddenly interrupts me."
    mc "Talk?"
    s 15j "Yes, talk. We need to talk now."
    "There's urgency in his tone." 
    "In fact, his entire demeanor is tense and his expression seems worried." 
    "Even his temper is short." 
    mc "Of course we can."
    s 11f "Good." 
    s "Let's go to your room." 
    s "And hurry." 
    s 12k "Before I lose my nerve." 
    show satori at thide
    hide satori
    "Satori hurries past me." 
    "I struggle to keep up as we slip back into the house and head upstairs."
    $ persistent.clear[5] = True
    $ renpy.save_persistent()
    return