label sayori_exclusive_1:
    scene bg club_day
    with wipeleft_scene
    "Man. Seems like no one wants to be bothered today."
    "I slump down into the nearest desk."
    "How am I supposed to occupy myself with something literature-related when I'm alone like this?"
    "I guess I could start reading the book Yuuri gave me, but I'm so bored that reading would only put me to sleep."
    "I close my eyes and end up listening in on Satori and Mateo's conversation."
    show satori 1g at t21
    show mateo 6d at t22
    s "We're probably gonna sound really lame compared to all the other clubs though."
    m "Hmm...well, we can't give up."
    m 1r "The festival is our chance to show everyone what literature is all about."
    m 1d "The problem is, the idea of a literature club sounds too dense and intellectual."
    m 3g "But it's not like that at all."
    m 3i "We just need a way of showing that to everyone."
    m 1r "Something that speaks to their creative minds."
    s 2h "That doesn't solve our problem though."
    m 6i "What problem?"
    s 3j "Even if we come up with the most fun idea ever, who's gonna come to a literature event in the first place?"
    s 3c "It's more important for us to figure out how to get people to actually show up."
    s 3b "We need to first accumulate an audience, then we can speak to their creative minds."
    show satori 1b
    "Wow, Satori really is taking this seriously."
    "It's rare to hear him deliberating like this."
    m 6q "Hmm...very good point."
    m 4x "In that case, do you think food will do the trick?"
    s 7x "The right food will!"
    m 1ag "Are you thinking what I'm thinking?"
    s 5 "Donuts!"
    m 1k "That's right! Natsuko would love to handle that."
    s 4r "Yeah! That works out perfectly!"
    m 3b "Now to work out the details of the event itself..."
    "I find myself smiling...thinking about those donuts."
    scene black with close_eyes
    "Also, I admire Satori's dedication to this club."
    "I have so much trouble finding any motivation at all."
    "Satori, on the other hand, can put his mind to anything and make it happen."
    "That's why I let him get on my case about things."
    "I wonder what it'd be like to see the world through his eyes?..."
    scene bg club_day with open_eyes
    mc "Gah---!"
    show satori 4aa at face
    "I open my eyes to see Satori's face filling my vision."
    "I nearly fall out of my chair."
    show satori at h11
    s 1aa "Aw...did I wake baby from her wittle nap?"
    mc "You scared me half to death, ya big doofus!"
    s 1j "Well, tough!"
    s 7ac "You shouldn't have been sleeping in the first place!"
    s 1i "Unfortunately for you, there's no such thing as the napping club!"
    "I grab Satori's arm and look into his face with excited eyes."
    mc "Dude...we need to start the Napping Club."
    s 1j "You stayed up late again, huh?"
    s 7ac "You know, now that you're in this club, you're gonna have less time for video games. So get used to it."
    mc "Fine, fine. You're always looking out for me, Satori."
    s 1k "Well...someone has to."
    mc "And therein lies the problem, my friend."
    mc "You look out for me better than you look out for yourself."
    mc "You talk about me staying up late when you started oversleeping last year and continue to do so."
    mc "The only reason you wake up on time now is so you can make sure I wake up on time."
    mc "You don't wake up for you. You do it for me."
    mc "Do you ever do anything for yourself?"
    s 10y "Um..."
    mc "In fact...what the hell are you even wearing?"
    s 1n "Eh?"
    "Satori scans himself curiously."
    s 1o "Oh...my new uniform?"
    s 1l "Yeah...I accidentally got the wrong size."
    s 1g "Is it...is it that noticeable?"
    mc "You look like a 6 year old trying to wear his father's business suit."
    show satori 1ab
    mc "See, this is exactly what I'm talking about."
    mc "If you cared about yourself, you would have paid more attention to what you were ordering."
    mc "You're not even wearing it properly."
    mc "Look at the other guys."
    show satori 1b
    mc "See how their blazers are nicely buttoned and their ties tucked in?"
    mc "Why is yours still unbuttoned?"
    mc "You specifically got a new one because the other one was too tight when buttoned up."
    mc "Jeez, come here."

    scene s_cg1_base
    show s_cg1_exp1
    with dissolve_cg
    "I stand up and start fixing Satori's tie."
    "I tighten it properly and button up the collar of his white undershirt."
    "I tuck the tail into his sweater vest."
    "Then I get to work buttoning his blazer from the bottom, working my way up."
    "Satori smirks a little."
    s "You...you really shouldn't do these kinds of things in front of people."
    s "They might get the wrong idea about us."
    "I look up at Satori curiously."
    "He's blushing a little."
    "I'm tempted to make this situation as weird as possible for him."
    "It amuses me so."
    mc "Since when do we care what people think about us?"
    mc "You scared you won't get a girlfriend if everyone thinks we're a couple?"
    "Satori's blush intensifies a bit."
    show s_cg1_exp2 at cgfade
    s "Well, no..."
    s "It's...it's the guys..."
    s "If they think we're a couple, then you won't be able to..."
    s "You know..."
    s "Get one of them to ask you out."
    mc "You know...I really appreciate your help..."
    mc "But... Why do you care so much about hooking me up with one of your friends?"
    s "Huh?"
    s "Ah---! N-n-no reason!"
    s "I was just... Uh..."
    hide s_cg1_exp2
    show s_cg1_exp4 at cgfade
    s "Jeez, sorry I said anything!"
    "He averts his eyes."
    "Hehe... he's adorable when he's flustered."
    "I finish buttoning up his blazer."
    mc "There. That's better."
    mc "You know you're dressed right when your tie, buttons and belt buckle line up perfectly in a straight line."
    "I look down and notice his pants are crooked, the belt buckle off to one side."
    mc "Ah, hold on..."
    s "H-hey--! [player], wait!"
    "I reach down, my fingers curling into the front of his pants and gripping the waistband."
    "With one assertive but gentle tug, I line the belt buckle with the buttons on Satori's blazer."
    mc "There we go."
    hide s_cg1_exp4
    show s_cg1_exp3 at cgfade
    s "Jeez... w-what'd you do that for?"
    s "I could've handled it myself!"
    "I look up at him, smiling playfully."
    mc "Well... Maybe I wanted to handle it today."
    hide s_cg1_exp3
    show s_cg1_exp5 at cgfade
    "Satori's face turns bright red."
    "He retreats a few steps."
    s "Gah!"
    s "W-w-why do you always say weird things like that?! Sheesh!"
    "I snicker triumphantly."
    "I just can't help myself sometimes."
    mc "Anyway, you look much better now."
    hide s_cg1_exp5
    show s_cg1_exp4 at cgfade
    s "Ack--...I can't stand the collar buttoned up like that."
    s "I can hardly breath."
    s "Feels like I'm being strangled."
    s "And I can barely move in this stiff blazer when it's all buttoned up."
    s "Ugh...it's not worth it at all."
    "Satori hastily unbuttons his blazer once more, along with his shirt collar."
    "He also loosens his tie and frees it from beneath his sweater vest."

    scene bg club_day
    with dissolve_cg
    show satori 5z at t11
    s "Ah...much better!"
    "Having disheveled himself once again, Satori stretches in relief."
    s 1j "You have some nerve to talk about {i}my{/i} wardrobe."
    s 7j "What about you? Where even {i}is{/i} your blazer?"
    mc "What do you mean? It's right he-..."
    "I check my waist, where I usually keep my blazer tied, only to find that it's gone."
    "I feel my face burn with embarrassment."
    mc "Oh, damn it!"
    s 1ac "You lost it, didn't you?"
    s 7ad "Again!"
    mc "I...didn't lose it, alright?"
    mc "I just..."
    mc "...Don't know where it is right now..."
    s 1o "..."
    s 5p "They mean the same thing, dingus!!"
    mc "Oh, shut up."
    mc "It's probably just in the lost and found again."
    s 7ac "Or hanging on the back of the chair in the detention room."
    s 3ac "Or lying in the hallway."
    s 7ac "Or in the cafeteria..."
    mc "Whatever!"
    mc "It always ends up in the lost and found anyway!"
    s 3ab "It wouldn't end up there if you would just wear it like a normal person!"
    mc "C'mon..."
    "I look around nervously before lowering my voice a bit."
    mc "You know why I keep it tied around my waist..."
    show satori 1b
    "I tug embarrassingly at my skirt."
    "I use the blazer as...well...extra coverage."
    "Satori grins devilishly and gestures towards the others."
    s 1aa "You really want to get their attention?"
    s 4aa "Leave the blazer in the lost and found."
    mc "Hey, I don't need to show off the goods in order to get their attention!"
    mc "I happen to be pretty friggin' charming!"
    s 10s "Okay, okay!"
    s 10l "It was just a joke..."
    mc "Well, anyway...try to focus a bit more on taking care of yourself, alright?"
    mc "If you wake up early, do it for your benefit."
    s 4i "Only if you agree to start going to bed at a reasonable hour."
    mc "Deal."
    s 10y "I guess we really are better at taking care of each other than ourselves, huh?"
    mc "Yeah. I think it's always been that way."
    show satori at t21 zorder 3
    show mateo 6k at t22 zorder 2
    m "Alright, guys!"
    "Mateo suddenly calls out."
    m 6b "Why don't we share our poems now?"
    s 5z "Sweet! I can't wait to read yours, [player]!"
    mc "Yeah...likewise..."
    "I fail to sound enthusiastic as Satori jogs to his desk to retrieve his poem."
    show satori behind mateo at thide
    return

label sayori_exclusive_2:
    scene bg club_day
    with wipeleft_scene
    show satori 2x at t11 zorder 2
    s "Hey, [player]!"
    s "I'm gonna go grab some supplies from another classroom."
    s 3a "Come with me."
    mc "What're the supplies for?"
    s 1a "To make posters and stuff for the festival."
    s 7a "We're looking for crayons, markers, glue sticks..."
    mc "Crayons and glue sticks?"
    mc "Are we trying to target creative 7 year olds for our event?"
    mc "We gonna throw together some macaroni pictures, too?"
    s 1j "Smarty pants."
    s 1a "You coming with me or not?"
    mc "Yeah, yeah. I'm coming."
    s 5z "Great. Hey, Mateo!"
    s 5x "We'll be back soon."
    show mateo 1d at f21
    show satori at t22
    m "Is that so?"
    m "Hm."
    m 3b "Don't you think [player] would benefit from spending some time in here reading instead?"
    show satori 5b
    m "I'm sure I can find her something productive to do."
    m 1w "In fact..."
    "Mateo grins at me."
    m "Maybe she'd like to help me with some things today."
    show satori 5i
    m 1s "I think that would be best."
    "What the..."
    "Mateo wants to..."
    "Spend time with me?"
    "I can feel my stomach tighten again."
    "I don't know what's gotten into him today."
    "Maybe he finally sees that I'm taking this club seriously?"
    "Whatever the case may be, I'm pretty curious to see where this is going."
    "I glance over pleadingly at Satori."
    "C'mon, man. Let me see what this jerk has planned for me."
    show satori 1ab
    stop music fadeout 2.0
    "But his expression changes."
    "He narrows his eyes as he steps closer to Mateo."
    show satori at f22
    show mateo at t21
    s 1ad "Well... with all due respect, Mister President..."
    s 1ae "I wasn't exactly asking your permission."
    show satori at t22
    show mateo 6h
    "I stare wide-eyed at Satori."
    "Where did this come from all of a sudden?"
    "Testosterone seems to fill the air as the two of them face-off."
    "Satori maintains his cold stare."
    show mateo 7aa
    "To my surprise, Mateo is the first to timidly look away."
    show mateo at f21
    m "...Alright. Fair enough."
    m 7ab "It was only a suggestion, anyway..."
    show mateo at t21
    show satori at f22
    s 1ab "C'mon, [player]. Let's go."
    show satori at thide
    hide satori
    show mateo at f21
    m 7z "Don't forget the poster paper."
    show mateo at t21
    "Mateo hisses that as Satori walks out of the room."
    "I follow quietly."

    scene bg corridor_day
    with dissolve_scene_half
    play music t8
    show satori 10k at t11 zorder 2
    "Once outside, Satori walks several feet before stopping and covering his face with his hand."
    "I quickly trot to his side."
    mc "Hey, Satori!"
    mc "You wanna maybe tell me what that was about?"
    show satori 1f
    "He shakes his head."
    "I start to worry."
    s 1h "I'm so sorry I had to do that."
    mc "Wh-what do you mean?"
    s 10g "I could tell you wanted to spend time with Mateo."
    s "I'm really sorry I had to ruin that for you."
    s 7g "But... I need your help."
    mc "...Oh!"
    mc "Well, hey, if you need help, I'm always here for you."
    mc "Forget about Mateo."
    mc "What do you need from me, buddy?"
    s 10d "You...you're the best, [player]."
    s 7g "The thing is..."
    "Satori looks around suspiciously."
    "Is he trying to make sure no one is listening?"
    "He leans in and whispers."
    s 1h "I forgot to write a poem last night!"
    mc "What, again?"
    mc "Oh, for goodness sake, Satori..."
    s 7i "Hey, I was kinda preoccupied playing video games with YOU last night!"
    s "And what about your poem?"
    s "I know you didn't do it last night either."
    mc "True, but I, at least, had the foresight to do it during lunch."
    mc "Why didn't you?"
    s 10e "Well... I... Um..."
    s 10l "I guess I didn't think of it..."
    mc "Well, that's just great."
    mc "So, while you're busy throwing together a poem, I'll be the one looking for supplies?"
    s 1l "Ehehe... That's the plan!"
    s 1f "You're not mad at me, are you?"
    mc "Sigh. Of course not."
    mc "I'm just glad you're okay."
    mc "Your freak-out back there had me a little concerned."
    s 1k "I'm sorry."
    s "That... That did get a little more intense than it should have."
    s 1g "I'm... I'm not sure why, but..."
    s "Something about how he said that..."
    s 4ao "It..."
    s "It made me want to punch him in the face."
    mc "..."
    "I'm little relieved to hear that I wasn't imagining the high tension between Satori and Mateo a few minutes ago."
    "There definitely seemed to be more to that than just the excuse to get me out of the room to help him."
    "That sudden spike of aggression, though..."
    mc "It's okay, Satori. I wanna punch him in the face, too."
    show satori 1a
    "He gives me a little smirk."
    "Curious as I may be, I decide it's best to let it go."
    "Whatever happened back there was probably just a guy-thing."
    mc "What're we even doing for the festival anyway?"
    mc "I mean...how do you make an event for literature?"
    s 7r "Oh, don't worry."
    s 7x "Mateo and I have everything planned out."
    s "We're doing a poetry performance."
    mc "A performance?"
    mc "Like...reciting poetry in front of people?"
    s 5z "Exactly!"
    s 8x "We're all gonna take turns on stage reading our favorite poems to everyone."
    "Wow, that sounds mind-numbingly boring."
    mc "Whoa, partner!"
    mc "That kind of excitement sounds like too much for people to handle."
    mc "I mean..."
    mc "We don't want to distract from the other events at the festival, you know."
    s 7j "Okay... First of all, no one thinks you're funny."
    s 7g "And secondly, you're not looking at this the right way at all!"
    s "We're not just reading the poems."
    s "We're performing them."
    s 7c "So, you gotta read the lines like,---"
    s 4d "Above my head, the last remaining star beckons to me."
    s 4q "I reach up and pluck it from from the curtain of night."
    s "I hold the glowing gem to my chest, absorbing its brilliant light."
    s 7k "The consequences of my selfish act soon become clear to me."
    s "For now, the sky has lost all of its dazzling stones."
    s "The moon, once surrounded by her children, now floats all alone."
    s 1e "And the world is shrouded in darkness, because of me."
    s 1ar "...Like that!"
    mc "... Wow. You've swayed me, Shakespeare."
    mc "When you perform it that way, it's guaranteed to only put half our audience to sleep."
    s 1ap "Oh, shut up."
    s "You're so uncultured."
    mc "C'mon, man."
    mc "I can't take you seriously when you talk like that."
    mc "I mean... It's awesome that you've got so much passion for this."
    mc "It just feels weird because I'm not used to seeing this side of you."
    mc "I didn't even know you liked poetry."
    mc "So hearing you sound so...articulate..."
    mc "Well..."
    mc "It's kind of attractive."
    show satori 1m
    s 10l "D-don't say things like that."
    s "It's embarrassing."
    s 10y "But...I guess it means I'm doing a good job."
    mc "You are."
    mc "And you're right."
    mc "I am uncultured."
    mc "But, who knows. Maybe the festival will change that."
    s 5s "Yeah! I'll make sure the festival changes us both for the better!"
    s 7aq "Hey, look. One of your favorite rooms!"
    "Satori stops in front of one of the empty detention rooms."
    "I look away with a scowl."
    "He chuckles in amusement as he peeks through the window."
    s 1aa "Well...it doesn't look like your blazer is in here..."
    mc "Eh? Of course not!"
    mc "I have it right..."
    mc "CRAP!"
    "Once again, my blazer is absent from my waist."
    s 7ap "Maybe you should learn to tie a proper knot."
    mc "Maybe you should learn to shut up."
    "Satori giggles once again."
    s 4z "Wow. So mature of you."
    s 7aa "C'mon, dummy. Let's go."
    "The two of us enter the classroom."

    scene bg classroom_day
    with dissolve_scene_half 

    "Satori wastes no time grabbing a blank sheet of paper from the closet and a pen from his pocket."
    show satori 1c at t11 zorder 2
    s "Alright. I'm gonna get started on my poem."
    s 7c "You ransack the closet."
    mc "Aye-aye, captain."
    hide satori
    with wipeleft
    "I start poking around in the closet."
    "I spot a full box of crayons and pull them down from the shelf."
    "The box is a little heavier than I anticipated."
    "Once the shelf is not longer supporting it, the box slips through my fingers."
    "I fumble, attempting to catch it with my other hand."
    "My fingers grip too late and the box bounces off my open palm."
    "A poor attempt to catch it again with my other hand just knocks it further from me."
    "The box loudly crashes to the ground and the crayons roll in all directions."
    mc "Shi..."
    show satori 7j at t11 zorder 2
    s "Hey! What're you doing?"
    "I quickly look up at Satori, trying to be cool."
    mc "What? Nothing."
    mc "What're you doing?"
    s 1o "What am I--..."
    s 5p "You KNOW I'm trying to write this poem!"
    mc "So, write your poem."
    mc "No one's stopping you."
    mc "Don't worry about what I'm doing. Worry about what you're doing."
    mc "Do your thing and I'll do mine."
    mc "Quit making things weird. Jeez."
    "Smooth."
    show satori 5i
    "Satori looks at me suspiciously for a few moments before slowly bringing his attention back to his poem."
    hide satori
    with wipeleft
    "As soon as his head is down, I drop to my knees and begin quickly scooping up the crayons, dumping them haphazardly into the box."
    "The fall caused some of the crayons to break."
    "By the time I'm finished, the box is bursting from the seams and the top no longer closes."
    "Crayons poke out of the top and sides."
    "I place the overflowing box on a desk."
    mc "There we go. Good as new."
    "I go back in the closet and start searching for the rest of the supplies."
    "Alright. I'm pretty sure I found everything."
    "Crayons, markers, glue sticks, poster paper..."
    "I even found some little bottles of glitter."
    "I can imagine the festive posters that can be made with this stuff."
    "I'm sure the local 2nd graders will be very impressed."
    mc "Hey, Satori."
    mc "I got all the stuff. You done yet?"
    show satori 5r at t11 zorder 2
    s "Just one second...there!"
    "Satori holds up his poem, looking it over with a whimsical smile."
    s 5z "Perfect. The best poem ever, just like I said it would be."
    mc "Sweet. Let's see it..."
    "I walk over and reach for the poem, but Satori quickly pulls it away."
    show satori 7i
    "He holds it high above his head."
    mc "H-Hey! What's the deal?"
    s 7j "You can't see it yet!"
    s 7ac "You have to wait until we share our poems in the club."
    mc "Are you serious?"
    s 1i "I sure am."
    s 3i "It wouldn't be fair to the others."
    mc "Ugh. Fine."
    mc "You're such a goodie-goodie. Here."
    "I take the supplies-- markers, crayons, glue sticks and glitter bottles folded in the poster paper-- put them into a box and thrust it into Satori's torso."
    "He quickly supports it with both arms."
    show satori 1b
    "His fingers clutch his poem beneath the load."
    mc "Now...when we get to the clubroom, I'll distract everyone while you take this stuff to your desk."
    mc "Slip the poem into your bag while they're not looking. Okay?"
    s 1s "Ah--! Good idea, [player]!"
    mc "It's the only kind I have!"
    s 1ap "Hmm...debatable." 
    mc "Oh, what do you know? Let's just go before they come looking for us."
    show satori at thide
    hide satori
    "We exit the classroom."
    
    stop music fadeout 2.0
    show satori_cg
    with dissolve_scene_half
    play music t9
    show s_cg2_base
    s "Hey, [player]..."
    mc "Yeah?"
    s "You know... This kinda takes me back to when we were kids."
    s "Remember?"
    s "I followed you everywhere and did everything you said."
    s "You'd get us into all kinds of trouble."
    s "But... You always seemed to be able to talk your way out of it."
    show s_cg2_exp1
    s "You're so clever and quick-witted."
    s "I...I've always admired that about you."
    s "I used to wish I could be just like you."
    s "And to be honest...I still kinda do."
    s "You're the most clever person I've ever known."
    s "And even now, all these years later..."
    s "You're still coming up with plans to get me out of the trouble you got me into in the first place."
    "I blush a little at the sentiment and the memories."
    mc "Satori..."
    hide s_cg2_exp1
    show s_cg2_exp2
    s "I know it's sappy, but...I'm really glad we're still best friends."
    s "I hope nothing ever changes that, you know?"
    s "I don't want anything about our friendship to change."
    mc "Really? I'm the exact opposite."
    mc "I look forward to change."
    hide s_cg2_exp2
    show s_cg2_exp3
    s "Huh? But, why?"
    mc "Because everything grows, Satori."
    mc "Just like us."
    mc "Every day, I feel like our bond grows stronger."
    mc "Our loyalty to each other grows stronger."
    mc "Our trust."
    mc "Don't you think?"
    mc "Are we not even closer now than ever?"
    s "I...I guess so. Yeah."
    mc "So, you see, our friendship is constantly changing."
    mc "It only gets deeper and deeper with each passing season."
    mc "With each rotation of the earth and with each trip around the sun."
    mc "In fact, the only thing I wouldn't change is the inevitability that everything will change."
    s "[player]...that's so poetic!"
    s "Maybe you should write it down and share it with the club!"
    mc "...No."
    mc "It's not for them."
    mc "Some poems..."
    mc "Are just for you and me."
    hide s_cg2_exp3
    show s_cg2_exp4
    "Satori suddenly looks at me in a way he never has before."
    "I smile and look away, but I can still feel his gaze linger."
    "I wonder if something changed just now?"
    "We walk back to the clubroom the rest of the way in silence."
    stop music fadeout 2.0
    scene bg club_day
    with dissolve_scene_half
    play music t3
    show satori 1a at t11 zorder 2
    mc "We're back!"
    show satori at t22
    show mateo 6d at f21 zorder 2
    m "That took longer than anticipated."
    m "I hope you found everything we'll need."
    mc "Sure did."
    mc "Sorry it took so long."
    mc "These teachers really need to learn to organize the stuff in their closets!"
    show satori 1b
    "I quickly make eye contact with Satori and shift my gaze to the back of the room."
    "He picks up on my cue instantly."
    s 1c "I'm gonna go set this stuff in the back."
    m 1t "Don't trouble yourself, Satori."
    m "I'll take it from here."
    "Mateo suddenly reaches for the supplies."
    show satori 1g
    "Satori gives me a worried look."
    "Time for me to step in."
    mc "I'll help too!"
    "I grab the flimsy crayon box."
    "It's barely holding together."
    "I give it a little squeeze."
    show satori 1n
    show mateo 1g
    "The box bursts at the seams and the crayons explode everywhere."
    mc "Oops...I'm so sorry!"
    mc "Ugh...I'm such a clumsy idiot..."
    "I look at Satori and gesture for him to continue heading to the back of the room."
    show satori 1a
    "He nods."
    s 1x "You help her clean those up, Mateo. I have this."
    hide satori
    m 1ab "Right."
    hide mateo
    "Mateo sinks to his knees and starts picking up the crayons."
    "I do the same."
    "To my surprise, Natsuko and Yuuri lay their books down and come help us."
    "As the 3 of them busily scoop up crayons, I look over at Satori."
    show satori 1b
    "He sets the supplies on his desk and inconspicuously slips his poem into his bag."
    show satori 1a
    "He gives me another nod."
    "Mission complete."
    hide satori
    "I smile and continue helping the others collect the crayons."
    show mateo 1d
    mc "So, Mateo... I know you didn't ask for it, but I also grabbed some bottles of glitter."
    mc "I figure most people are attracted to shiny things anyway, so it should draw their attention to the posters."
    mc "That might work, right?" 
    m "Hm... that's true."
    m 1b "Good idea, [player]."
    show satori 7z
    s "Those are the only kind she has!"
    hide mateo
    show satori 1aq
    "Satori and I grin at each other knowingly."
    "I guess we do make quite a team."
    hide satori
    show mateo 6b
    m "Alright, guys! Are you ready to share your poems?"
    mc "Guess I should go grab mine."
    return